opinions/united_states/state/nh.py
tests/tests.py

regex was only looking for comma as separator and they decided to use a period for one line. New regex can handle a comma, period, or any number of whitespaces. tests.py was also updated to reflect this. sample_caller succeeds.

Fixes New Hampshire Supreme Court

---

opinions/united_states/state/fladistctapp_3.py

An attempt to fix scraping of case names on this page
http://www.3dca.flcourts.org/Opinions/Opinions2015-07-22.shtml
where the case name is followed by some comment like this:
<td> <p> case name <br> comment </p> </td>

Fixes Florida 3rd District Court of Appeal scraper

---

lib/string_utils.py
opinions/united_states/federal_appellate/scotus_chambers.py
opinions/united_states/federal_appellate/scotus_relating.py
opinions/united_states/federal_appellate/scotus_slip.py
tests/examples/opinions/united_states/scotus_chambers_example.html
tests/examples/opinions/united_states/scotus_relating_example.html
tests/examples/opinions/united_states/scotus_slip_example.html

Updated scotus scrapers and associated example html files to reflect new site format, which now includes a 'Revised' column in the tables.  Also added a new convert_date_string() method to lib/string_utils.py to get valid date() object form a given date string

Fixing broken scotus scrapers

---

opinions/opinion_template.py
opinions/united_states/state/ny.py
tests/examples/opinions/united_states/ny_example.html
tests/examples/opinions/united_states/ny_example_2.html
tests/examples/opinions/united_states/ny_example_3.html
tests/examples/opinions/united_states/ny_example_4.html

Fixing New York Court of Appeals scraper, which broke due to some slight page format changes.  Updating html examples.  Updating opinion_template.py to referance/demonstarte new convert_date_string() function.

Fixing New York Court of Appeals scraper

---

opinions/united_states/state/nh.py
tests/examples/opinions/united_states/nh_example_2.html
tests/tests.py

The court recently published a case whose link text exhibited a new format by including multiple (2) case titles and multiple (2) docket numbers, separated by <br>.  This commit will detect both case names, clean them up, then glue them together.  It will also detect both docket numbers, and concatenate them with a ',' delimiter.  I've added a new html example for Feb2016 page to test against this use case in the future.  I also changed one line in tests/test.py, which was calling a property on the nh.py Site() class, which I renamed for clarity's sake.

Fixing NH scraper to properly parse multi-case information associated with single pdf

---

opinions/united_states/state/nd.py
opinions/united_states/state/ndctapp.py
tests/examples/opinions/united_states/nd_example_3.html
tests/examples/opinions/united_states/ndctapp_example_3.html

The changes here do not present the most efficient approach to scraping the nd court page, as the new logic rebuilds the entire page's case data map for each of the standard getter methods.  However, the resource page never has that many results, and this new logic is still snappy/quick enough (no human noticable difference on my machine).  Ultimately, I think it makes the two scrapers' code more intelligible, simple, and a bit less repetitive.  Also, before this change, the nd.py scrapper was failing on the Aug2007 resource page (the most recent resource page to have an Appeal case posted).  That issue is fixed in this commit, and I've included the Aug2007 html as a test resource for both scrapers so that future changes must maintain their ability to scrape that page (assuming the whole …

Simplifying, documenting, and fixing nd/ndctapp scrapers.

---

opinions/united_states/state/nd.py

even if the clerk mistakenly types multiple spaces, or tabs, between the regex pattern words.  This also ensures that the citation string pulled from the page is sanitized with single space delimiters instead of multiple spaces/tabs, if the clerk types those.  There are no examples of this happening yet, but since the text of these pages is hand types, this is a safety precaution in case it does ever happen.

Added fix to nd.py to ensure that we capture the citation string effectively

---

opinions/united_states/state/idaho_civil.py
tests/examples/opinions/united_states/idahoctapp_criminal_example_2.html
tests/tests.py

Unlike the idaho_civil resource page, the idahoctapp_criminal resource page uses 'ORDER' instead of 'Order' as the anchor text for order case PDF links.  I suspect this is just a one-off incident, but I've gone ahead and added a test example of the html that was breaking the idahoctapp_criminal scraper.

Fixing idahoctapp_criminal by way of idaho_civil

---

opinions/united_states/state/ill.py
tests/examples/opinions/united_states/ill_example.html

Thankfully, the court has added an id attribute to the table holding the decisions information which allows for much simpler/standardized parsing of the target data.  Since the html format of the site has changes, I haven't added a new html example, but overwritten the old html example with the new html format from current resource page, as there is no need for current/future changes to work with the old/outdated format.

Fixing ill scraper

---

opinions/united_states/state/nyappdiv_3rd.py

This is my fault.  My last commit broke the handling on those, as I was unaware of them at the time.

Fixing nyappdiv_3rd scraper to handle human typos that were discovered on older pages

---

opinions/united_states/state/colo.py
opinions/united_states/state/fladistctapp_2.py
opinions/united_states/state/nyappdiv_3rd.py
opinions/united_states/state/wash.py
tests/examples/opinions/united_states/coloctapp_example_2.html
tests/examples/opinions/united_states/fladistctapp_2_example_3.html

coloctapp was breaking due to regex in colo, washctapp_p was breaking due to regex in wash, and fladistctapp_2 was breaking due to bad formatting on one of the current resource pages.  I've added a new test for coloctapp and fladistctapp_2 to account for new edge formatting cases.  I updated nyappdiv_3rd to have a more strict regex test based on recent discussion with @mlissner about our policy to fail loudly.  I wanted to add a test for coloctapp, but couldn't get the current html to fail the unit tests.  When I would execute this scraper and then dump the json from within the python terminal, it would fail.  But when I added the html to the unit tests, it would not (I believe the naming convention was correct, and saw the counter for coloctapp tests increment by one after adding the new …

Fixing colo, fladistctapp_2, wash. Improving nyappdiv_3rd.

---

opinions/united_states/state/ky.py

This commit includes a restructuring of how/when the opinion data is parsed for the ky scraper.  This allows us to get around opinions that are published in the primary search portal, but are restricted in the secondary search portal used to retrieve the name.  Incidentally, this commit also fixes a bug that was buried in the ky scraper that presented the potential for bad data to be pulled by converting a docket number ending in a zero, or multiple zeros to another number altogether.  For example, 000410 would have been converted to 41 instead of 410, and if there was another case for the same year with a legitimate docket number of 41 (000041) that case name would be pulled and used for the 000410 case record.  Assuming they number their cases in chronological order, it's pretty much …

Fixing ky scraper

---

opinions/united_states/state/ill.py
tests/examples/opinions/united_states/ill_example_2.html

The ill court recently posted opinions that have non-standard formatting (excluded precedential status strings, and docket numbers broken over multiple lines), which was causing the scraper to fail.  This commit fixes the parsing to handle these cases, and includes a new test html file to test against them.

Fixing ill scraper to handle non-standard formatting

---

juriscraper/opinions/united_states/federal_appellate/ca6.py
juriscraper/opinions/united_states/state/kan.py
tests/examples/opinions/united_states/ca6_example.html

ca6 was failing because their site url changed, as well as their site format.  I've replaced the old example file with the new format's source.  kan was not broken, but it has a bug that was preventing some cases (both kan and kanctapp) from getting discovered. No new kan/kanctapp example files necessary, as the business logic remains the same.

Fixing ca6 and kan/kanctapp

---

juriscraper/__init__.py
juriscraper/opinions/united_states/state/fladistctapp_2.py
tests/examples/opinions/united_states/fladistctapp_2_example_4.html

Scraper is currently breaking due to space in the docket number.  This fix removed spaces form the raw_docket text string before regex matching.  Added new test tile.  Incremented version number.

Fixing fladistctapp_2 scraper to handle typo in docket number

---

juriscraper/__init__.py
juriscraper/opinions/united_states/state/mass.py
tests/examples/opinions/united_states/mass_example_2.xml

Adjusting regex to handle semicolon-delimited docket numbers in addition to comma-delimited.  Adding new test file.  Bumping version number.

Fixing mass scraper

---

juriscraper/opinions/united_states/state/colo.py

Colo has had a case record without a name for a few months now.  It has been holding up our colo and coloctapp scraping.  We've asked colo multiple times to fix it, but they haven't been very responsive.  This commit includes some logic to assign 'Unknown Title' to cases without titles.  This is not an ideal fix.  By 2017, the problematic case may be outside the scraper's range.  I've added a comment for future commiters to intermittently check on this, and remove the logic added by this commit when appropriate.

'Fixing' colo scraper

---

juriscraper/opinions/united_states/state/fladistctapp_5.py
tests/examples/opinions/united_states/fladistctapp_5_example_2.html

Court deviated from their 'standard' way of formatting their text, which was causing scraper to fail.

Fixing fladistctapp_5

---

juriscraper/opinions/united_states/state/vt_p.py
tests/examples/opinions/united_states/vt_p_example_2.html

There are some bogus records at the bottom of the page.  There are a lot of cases on the page in general, 130+.  Since we are only concerned about the newest cases, I've added a limit to extract, at most, the 100 most recent cases.  This solves the problem presented by the bogus records and reduces the network load by a bit.  That being said, the bogus records looks like they are valid opinions that were simply improperly entered.  I will try to reach out to the court to have them fix it.  Added new text file.

Fixing vt_p

---

juriscraper/AbstractSite.py
juriscraper/__init__.py
juriscraper/lib/date_utils.py
tests/test_everything.py

Now the logic will only fix typoed dates for the current year.  Expanded logging to be more informative.

Second try at future-date-typo-fixing logic

---

juriscraper/__init__.py
juriscraper/opinions/united_states/state/colo.py

Fixing issue in cleanup_content() that was causing coloctapp to flop, removing unused method, and added new functionality to get direct pdf links.  Also added logic to parse case name from resource url/page, which allowed me to get rid of the bad 'Unknown Title' logic.

Fixing colo/coloctapp

---

juriscraper/opinions/united_states/state/wyo.py

The url was bad.  I must have screwed that up in my last commit.  I adjusted it to pull the results for the current year because there were strange issues when pulling all results where it would limit at 200 results and not grab the most recent, despite there being no such 200 limit in a browser.

Fixing wyo

---

juriscraper/opinions/united_states/state/__init__.py
juriscraper/opinions/united_states/state/minnag.py
tests/examples/opinions/united_states/minnag_example.html

This adds a scraper for Minnesota AG opinions, per #168. This passes the tests, and the output from `sample_caller` looks good to me.

Add Minnesota Attorney General Opinions

---

README.rst
juriscraper/lib/log_tools.py
juriscraper/pacerdocket.py
tests/examples/pacer/dockets/fake-rss/dcd.html
tests/examples/pacer/dockets/fake-rss/dcd.json
tests/examples/pacer/dockets/fake-rss/mad.html
tests/examples/pacer/dockets/fake-rss/mad.json
tests/test_pacer.py

* Some improvements to README.rst w/r/t running without installation.
* Two tests for faked-up RSS (cf. https://github.com/bdheath/Big-Cases/pull/3)
* An (example?) driver for running district court dockets frm the command-line. Very helpful for iterative parser testing cycles.

doc fixes, rss tests, and a command-line driver

---

juriscraper/pacer/notes.md

document_link.pl: Returns doc1 links given caseid and document-specific info
show_case_doc: Returns doc1 link given caseid and document number only (district only)
Note goDLS() is different in BK

notes.md docs: document_link, show_case_docs, goDLS()

---

juriscraper/pacer/notes.md

Turns out the mobile document count inclues unnumbered minute entries
(for those courts that use them), so it is not necessarily the same as
the highest numbered docket entry number. This makes it a little less
useful.

notes.md: Clarify mobile count limitations.

---

juriscraper/pacer/rss_feeds.py

Cleanup before my other work. Let's not get whitespace changes mixed
with functional ones.
Predecessor for fixes to
https://github.com/freelawproject/recap/issues/248
but filing this as a separate PR to avoid this inadvertently getting squashed with functional changes.
Lemme know if you'd rather I not do it this way.
(Note that recent changes to `docket_report.py` have a substantial number of PEP8 failures, but since I don't touch it I'm not going to address them now.)

rss_feeds.py: PEP8 fixes

---

juriscraper/pacer/rss_feeds.py

This is important to being able to debug the parser without repeatedly
pounding on the server, as well as being able to give it XML that the
server would never produce, exactly (e.g. a limited set with a single
specific entry, or maybe a specific type of entry)
This was really helpful for fixing freelawproject/recap#248

rss_feeds.py: Allow input from stdin

---

juriscraper/pacer/rss_feeds.py

Yet another outgrowth of  freelawproject/recap#248 work.
First, favor the prevailing style and use `u''` strings.
Substantially improve the documentation of `docket_entries()` and the regexs it uses at the top of the class. In the abstract, it's really tough to debug and figure out what's going on without this kind of thing.
Further, clarify the docstring of docket_entries() and the nonobvious peculiarity that it does not return minute orders without attached documents.
Next, broaden the `short_desc_regex` so it does not magically skip entries with no attached document. The choice is made explicit with `if not all([doc1_url.strip(), de[u'document_number']]):` and it's not productive to bury a restriction like that hidden in the regex. Especially because it is a bad restriction that should …

rss_feeds.py: doc+ docket_entries() & broaden short_desc_regex

---

juriscraper/pacer/appellate_docket.py
juriscraper/pacer/docket_report.py
tests/examples/pacer/dockets/appellate/ca1.json
tests/examples/pacer/dockets/appellate/ca11_1.json
tests/examples/pacer/dockets/appellate/ca11_2.json
tests/examples/pacer/dockets/appellate/ca1_2.json
tests/examples/pacer/dockets/appellate/ca1_3.json
tests/examples/pacer/dockets/appellate/ca9_1.json
tests/examples/pacer/dockets/appellate/ca9_2.json

Dont't squash the first 2 commits. Do you want them in a separate PR?
* Move the `_br_split()` function to BaseDocketReport so other subclasses can use it. Although I had originally used it more, I ended up switching most but not all to `redelimit_p()` instead, because `_br_split()` only returns text content and can't parse more structured stuff. (This suggests it is poorly named.)
* PEP8 fixes as reported by flake8
* And then all the rest: Parse HTML parties, plus a few more cleanups later.
* Update tests.

In Appellate parser, parse the party HTML information rather than including it raw.

---

juriscraper/lib/html_utils.py

Stop converting `</br>` into `<br/>`
As noted in my comment in #219: https://github.com/freelawproject/juriscraper/pull/219/files/e92373e61b8751b9482bba8668aa41212f16f35c#r191602446
`</br>` is not the same as `<br/>`.
The only valid HTML choice is `<br>`.
In XML or XHTML, all tags need to be closed, so that is normally
`<br/>`, but sometimes `<br />` and on much rarer occasions (but sometimes
seen in CMECF), it is `<br></br>`.
Transforming `</br>` into `<br/>` turns `<br></br>` into` <br><br/>` aka `<br><br>`.
That is, this transformation doubles each `<br>`, and thus doubles the
vertical space. That's especially troubling in appellate where a
double `<br>` is actually a semantic delimiter (in party parsing).
So anyhow, just cut it out.
For the tests that run for me, this fix actually …

html_utils.py:clean_html() Remove alleged "fix" for </br>

---

juriscraper/pacer/appellate_docket.py

First commit makes the second commit unreadable IMNSHO, hence the separation and the nonsquash preference.
(Private conversation lead to this fixup PR, sorry for the brevity herein).

Properly parse date fields in appellate party info

---

juriscraper/pacer/appellate_docket.py

1. Linting cleanups.
2. AppellateDocket:_get_case_name() Broaden xpath
Be far less specific in the XPath to get the case name. Don't look for
fixed strings that are highl court-dependent, instead use the NEW
SECTION comment markers.
After we find the comment, take the next descendant table that has
boldface in its first row, and return its second row.
This fixes cavc parsing.
3. Needs tests.

2018.08.08.appellate cavc

---

README.rst
juriscraper/AbstractSite.py
juriscraper/opinions/united_states/federal_special/tax.py
juriscraper/opinions/united_states/state/mdag.py
juriscraper/opinions/united_states/state/nyappterm_1st.py
juriscraper/opinions/united_states/state/ohio.py
juriscraper/opinions/united_states/state/sd.py
juriscraper/opinions/united_states/state/tex.py
juriscraper/opinions/united_states_backscrapers/federal_appellate/ca5.py

I changed the readme to instruct the developer to install phantomjs into /usr/local/bin.  The "executable_path" parameter is possibly not necessary if phantomjs is already in $PATH.  I hardcoded the executable_path in AbstractSite module, so that there is only one place to replace the path if there are people still using ```/usr/local/phantomjs/phantomjs```.  If we require and presume that phantomjs is installed into a ```PATH``` directory, much of this and older code could possibly be removed entirely.

use phantomjs path from ansible config

---

requirements.txt

I found where BeautifulSoup is mentioned in the juriscraper code.  It was mentioned in a docstring for one of the AbstractSite methods, where it was contemplated that it might be used by other developers.  I found the docstring when I was working on the oral argument scrapers for Mississippi.
In a previous discussion concerning the potential addition of bs4 as a requirement of the juriscraper package, I found that even the tree objects in the lxml.xpath elements could be used in a similar way to the example of bad practice that was presented to me (i.e. one can easily use ```el.getnext().getnext()...```.
I stated that I also didn't like using bs4 in that manner, but preferred the css selector syntax over the xpath syntax.  This was mostly due to familiarity and xpath seems to be very …

added cssselect to reqs

---

juriscraper/report.py
juriscraper/sample_caller.py
juriscraper/templates/__init__.py
juriscraper/templates/report.html.jinja2
requirements-dev.txt

This PR adds light instrumentation to the sample_caller runs, where exceptions and total items scraped are counted for each scraper ('module_string'). At the end of the run, if the`--report` option is enabled, a `report.html` file is created in the project root directory.
An example of a real report that this generates is [here](https://juriscraper.netlify.com/)
I believe this adds obvious value over trying to run sample_caller one scraper at a time and "see" if it failed or not.
Also jinja2 is added only as a dev dependency.

Collect stats on sample_caller runs and optionally report them

---

juriscraper/opinions/united_states/state/nh.py

Fixes #293.
Loosen regex to allow for better name matches.
Make the regex multiline and allow for multiple contiguous whitespace characters, to account for irregularities in the HTML.

Fix opinions.united_states.state.nh

---

juriscraper/opinions/united_states/federal_special/tax.py

Tax Court had a mislabeled reporter.  This was fixed.
Use of the function against our data set found a few edge cases that are now reflected in the regex and parsing.

Fix Text Extraction for Tax Court

---

juriscraper/lib/models.py
juriscraper/opinions/united_states/federal_special/tax.py
setup.py

This PR bumps the version to 1.26.27.
It moves a brand new function back into CL.
It adds a lib.models.py file.
Fixes the text extraction metadata dictionary for the tax court.
Also updates the setup.py file to work better with pip installations.

283 text parsing

---

juriscraper/pacer/http.py
juriscraper/pacer/utils.py

As discussed in #311, fixes re-login logic to catch cases where the PACER request returns a text file. When a text file was returned the existing session login check couldn't parse that it was a text file and an unnecessary re-login would be triggered.

Re-login triggered by text file return

---

juriscraper/opinions/united_states/federal_appellate/ca4.py

CA4 switched to https, which breaks our earlier code. Easy fix.

fix(scrapers) fix ca4 scraper

---

README.rst
requirements.txt

- the `requests==2.20.0` req should be a `>=`. Projects using a strict lock file (i.e pipenv or poetry) can end up with unlockable requirements based on not allowing higher versions of requests.
- adds badges back to the README.

Min Req for Requests, add Badges

---

.github/workflows/pypi.yml

Use our forked deploy pypi
This was viewed as a security risk.
This PR should also trigger a release of v.2.0.3

fix(pypi.yml): Use freelawproject/deploy-pypi@v1

---

juriscraper/pacer/docket_report.py

When run from the command-line, as python -m
juriscraper.pacer.docket_report, we read the file and must no longer
call .decode() as of Python3.
Fixes:
File "/Users/jhawk/src/juriscraper/juriscraper/pacer/docket_report.py", line 1284, in <module>
text = f.read().decode("utf-8")
AttributeError: 'str' object has no attribute 'decode'

fix(pacer/docket_report.py): python3 support on command-line

---

juriscraper/opinions/united_states_backscrapers/state/me.py

PR adds backslapper for years 2016 to 2020 for Maine SJC
Maine was briefly down - but that extended into last year.  So I added a simple backscraper to handle these older cases.

feat(backscraper-maine): Add simple backscraper for 2016-2020 opinions

---

juriscraper/opinions/united_states/state/me.py

PR addresses bug in Maine scraper. #372 
The old url redirects to the current page,
but because of the redirect the
download filepaths are still failing
Update url to new landing page

fix(maine): Update url for scraping

---

juriscraper/pacer/utils.py

Added exception when server response doesn't return a valid HTML page to scrap free opinions.
Some court's servers block requests to scrap free opinion documents. But if the returned page is not a proper HTML page, the parse fails and this error it's not properly cought.
Closes: #418

Added exception when server response doesn't return a valid HTML page to scrap free opinions

---

CHANGES.md
juriscraper/opinions/united_states/federal_appellate/ca10.py
setup.py
tests/examples/opinions/united_states/ca10_example.compare.json
tests/examples/opinions/united_states/ca10_example.xml

The RSS feed changed its XML document structure. The scraper was updated to adapt to the new document structure.
The test case included only has 'Unpublished' examples. It's not possible to search for examples in XML with status 'Published' because the RSS feed is replaced every day.
http://www.ca10.uscourts.gov/opinions/new/daily_decisions.rss
Closes #417

Updated XML structure for opinions from the Court of Appeals for the Tenth Circuit

---

.github/workflows/tests.yml
requirements.txt

Library `feedparser` 5.2.1 fails with Python 3.9 and 3.10. Version **6.0.8** works with supported Python versions **3.7 to 3.10**. 
Close: #422

Adds support for Python 3.9 and 3.10

---

juriscraper/opinions/united_states_backscrapers/administrative_agency/olc.py

Adds self.cases = [] to the download_backwards method.   This removes the snowball
effect where cases continue to build up and become reprocessed.

feat(olc-bs): Update backscraper

---

juriscraper/opinions/united_states/state/conn.py
juriscraper/opinions/united_states/state/connappct.py
tests/examples/opinions/united_states/connappct_example_4.compare.json
tests/examples/opinions/united_states/connappct_example_4.html

Also changed super class to `OpinionSiteLinear`.
Fixes: #479 
Fixes: #[COURTLISTENER-220](https://sentry.io/organizations/freelawproject/issues/2929913663/?referrer=github_integration)

Fixes docket and case name's separator for Connecticut Appellate Court 

---

juriscraper/pacer/http.py

Closes #482 
Closes [COURTLISTENER-22A](https://sentry.io/organizations/freelawproject/issues/2936179947/?referrer=github_integration)

Add exception when PACER loging reply is not a valid JSON object

---

CHANGES.md
juriscraper/pacer/reports.py
setup.py
tests/network/test_PacerFreeOpinionsTest.py

- Added new method `download_pdf_magic_link()` in `BaseReport` in order to support fetching free PACER documents using a magic link.
- The download is processed without being logged in PACER.
- Added a Test case to ensure download fails if the magic link is invalid or expired

Fix fetch free PACER documents using magic link

---

.pre-commit-config.yaml

- Locked black dependency to click=8.0.4 to avoid python 3.10 incompatibility error.

Fix pre-commit black error

---

juriscraper/lib/html_utils.py
juriscraper/pacer/reports.py
juriscraper/pacer/utils.py
tests/network/test_PacerFreeOpinionsTest.py

After testing sentry errors that were throwing these error messages: `Unable to download PDF. PDF not served as binary data and unable to find iframe src attribute.`
I found three reasons:
1.- `The document is not available.`
The text to compare and detect this error it's currently `This document is not available` so I changed the text to compare to `document is not available` in order to cover the two versions with `This` and `The`
2.- `This document is currently Under Seal and not available to the general public.`
Currently, to detect a sealed document error we look for the text `Sealed Document` so to cover this sealed error version I added the text `Under Seal`
3.- Magic link document:
Since we don't log in to PACER when downloading a magic link document if the document is unavailable …

Fixes PACER download PDF error messages

---

juriscraper/opinions/united_states/state/mich.py

We found a handy api but it appears
the wrong key was being used to get
to the supreme court opinions in the
elastic results.

fix(michigan): Michigan supreme court tweak

---

juriscraper/opinions/united_states/federal_special/tax.py
tests/examples/opinions/united_states/tax_example.compare.json

Fix tax scraper for changes to website.
Updated endpoints and changes to the website broke the scraper again

Fix Tax Scraper Again

---

juriscraper/pacer/docket_report.py

With input data court_id='cacd' and pacer_case_id='806502' received unhandled exception `ParserError("String does not contain a date: %s", timestr)` here: `juriscraper/lib/string_utils.py, line 510` in convert_date_string method.
This exception occurs when date_filed_str (docket_report.py, line 964) contains only white spaces. There is no check for such cases inside the convert_date_string method. 
P.S.
License agreement is on the way. It takes some time for me to print/sign/scan it.

Check that input date string is not empty in docket_report.py

---

CHANGES.md
setup.py

Seems that the last version 2.5.12 didn't get the updates for NEFs attachments. 
Maybe because the release changes are until the date I added the commit tag?

Version bump v2.5.13

---

juriscraper/pacer/http.py
tests/network/test_PacerFreeOpinionsTest.py

Working on the `DownloadConfirmationPage` Courtlistener integration I found a couple more cases when a `PacerLoginException` error is raised due to the download confirmation page is not available.
The exceptions added are:
When looking for a download confirmation page sometimes an appellate attachment page is returned instead, see:
https://ecf.ca8.uscourts.gov/n/beam/servlet/TransportRoom?servlet=ShowDoc&pacer=i&dls_id=00802251695
Sometimes the document is completely unavailable and an error message is shown, see:
https://ecf.ca11.uscourts.gov/n/beam/servlet/TransportRoom?servlet=ShowDoc/009033568259
So in these cases, no `PacerLoginException` will be raised and we will just return an empty dict for the `DownloadConfirmationPage` report (Cases where we won't be able to get the document …

More exceptions to avoid asking for login again into PACER

---

juriscraper/pacer/download_confirmation_page.py
juriscraper/pacer/reports.py
juriscraper/pacer/utils.py
tests/network/test_PacerFreeOpinionsTest.py

Seems that we need to skip the attachment page for appellate documents with attachments so that with this fix we can:
- Skip the appellate attachment page when querying the download confirmation page
- Skip the appellate attachment page when downloading the free document
In a next stage, we should also parse the attachment page for appellate courts since they have a different format than non-appellate.

Skip attachment page for appellate documents

---

juriscraper/pacer/email.py
tests/examples/pacer/nda/ca5_2.json
tests/examples/pacer/nda/ca5_2.txt

One small fix more:
Some notifications contain more than one "filed on" or "Filed on" strings, we were ignoring the case so an error was raised on those notifications,  the line that contains the filed date is always lowercased.

Fix getting filed date on notifications

---

CHANGES.md
juriscraper/pacer/http.py
juriscraper/pacer/reports.py
tests/local/test_PacerNeedLoginTest.py
tests/network/test_PacerFreeOpinionsTest.py

It turns out that r.text makes calls to chardet each time it is called. That's
not great because chardet can be slow and use a lot of memory, particularly
when checking PDFs.
Instead of doing that or checking if things are PDFs all the time, simply use
the binary content instead of the text.
Fixes: https://github.com/freelawproject/juriscraper/issues/564
Relates to: https://github.com/psf/requests/issues/6250

564 chardet performance binary content

---

juriscraper/pacer/reports.py
tests/network/test_PacerFreeOpinionsTest.py

Seems that PDFs downloads returned within a `window.location` were failing.
The problem was that the URL was being malformed:
https://ecf.azd.uscourts.gov b'/cgi-bin/show_temp.pl?file=23976857-0--126044.pdf&type=application/pdf'
Since the regex works within bytes so we needed to decode the URL instead of just casting to `str`

520 Fixes redirected pdfs download

---

juriscraper/pacer/download_confirmation_page.py
tests/network/test_PacerFreeOpinionsTest.py

This PR is related to the weird error we received in https://github.com/freelawproject/juriscraper/issues/582
This was an NDA, when adding a docket entry for an NDA we get the document number either from the download confirmation page or from the PDF, the main problem here is that the document is returned directly and no Download confirmation is displayed (seems to be a free document). So when trying to parse the download confirmation page over the PDF binary the error `ValueError: Invalid tag name 'mU0007EU0FFFD...` is raised.
To solve this problem I added a condition to check that the data returned when querying the Download confirmation page is not a PDF, so if the document is free and no confirmation page is shown, we consider it a no valid page so no data is returned from …

Avoid parsing a download confirmation page when the PDF is returned directly

---

juriscraper/lib/html_utils.py
tests/examples/pacer/case_queries/case_query_error.html
tests/examples/pacer/case_queries/case_query_error.json

This fixes #607, the problem is due to bad HTML escaped chars in this case `&#03` equivalent to 0x3 which is a no valid XML byte. 
Since the char is escaped can't be removed by the current method that fixes invalid XML bytes in `clean_html`, so then when the escaped char is converted to bytes the parsing fails. 
To solve it I added a regex that removes escaped chars from `&#01` or `&#1` to `&#08` or` &#8` equivalent to `0x1` to `0x8` bytes that are not XML valid.
Let me know what you think!

607 Fix remove bad HTML escaped chars

---

juriscraper/pacer/appellate_attachment_page.py
tests/examples/pacer/appellate_attachment_pages/ca1_46307.html
tests/examples/pacer/appellate_attachment_pages/ca1_46307.json

This fixes #612.
The error was due to an attachment row with a blank description. Then the list of text elements found in a row contains one less element raising the index error.
To solve it, now to extract the `page_count` I changed the index to the last element `[-1]` since it's always in the last cell.
To extract the `description`,  the `[-2]` element is selected based on all the cells found in a row (not only the ones that contain text) since the description is always before the page count (last element).
There is an error in tests, Bill told me is solved in #614 so once it's merged I'll rebase it so tests pass.
Let me know what you think.

612 Fixes index error when parsing appellate attachment page

---

juriscraper/pacer/appellate_docket.py
tests/examples/pacer/dockets/appellate/cadc_1.html
tests/examples/pacer/dockets/appellate/cadc_1.json

This PR Fixes #617.
- The problem here is the `Originating Court Information` table is available, however, the table only contains two rows one for the title and one with the text "None".
In order to solve it, we check if the only data we have within the `Originating Court Information` table (besides the title) is "None" if so an empty dict is returned. This approach will allow us to detect some other possible variations for example in case only the first row is "None" but if there are other rows with good data an error will be raised and we could add support for that example.
I detected a couple of small adjust in this example:
- Case Type Information, here point 2) and 3) exist but they are blank. So I added within the parsing conditions if it is an empty string the data is not added, …

617 Fixes index error if originating_court_information is no available

---

juriscraper/opinions/united_states/federal_special/cavc.py

Fix adds hardcoded date for tests.  Otherwise we slowly lose the one month period associated with the testing file.

tests(cavc): Fix test with hardcoded test date

---

juriscraper/lib/test_utils.py
juriscraper/pacer/http.py
tests/local/test_PacerNeedLoginTest.py
tests/network/test_PacerFreeOpinionsTest.py

As described in [#2160 ](https://github.com/freelawproject/courtlistener/issues/2160)sometimes a PACER login page is shown after a GET request, even though cookies are still valid. Usually doing additional requests solve the problem and the requested content is returned.
So in this PR, I added some code to do 1 additional GET request after `check_if_logged_in_page` returns `False`. So this would save retries and hopefully fewer PACERLoginExceptions would be raised into Sentry.
This logic only applies to PACER GET requests, since we don't have problems with POST requests according to sentry.
I did some tests in CL using this approach and seems to work, without this logic on a failing `fetch_attachment_page` task, it took on average 4-5 retries or failed to get the attachment page.  
While …

Do and additional GET request when a PACER login page is returned.

---

juriscraper/opinions/united_states/state/mass.py
juriscraper/opinions/united_states/state/massappct.py
juriscraper/opinions/united_states/state/massappct_u.py
tests/examples/opinions/united_states/mass_example.compare.json
tests/examples/opinions/united_states/mass_example.html
tests/examples/opinions/united_states/massappct_example.compare.json
tests/examples/opinions/united_states/massappct_example.html
tests/examples/opinions/united_states/massappct_u_example.compare.json
tests/local/test_ScraperSpotTest.py

PR Fixes #207 
PR updates scraper and simplifies Massachusetts and Massachusetts Appeals Courts.
PR also fixes what appears like a mistake in URL generation for 128archive, which is the unpublished appeals court cases.
The discussion in 207 was about parsing pdfs or something but that has been replaced with with the 128 archive which houses all the unpublished opinions for the appeals court.  So that long issue can be closed with these three changes.

Fix Massachusetts Scrapers

---

juriscraper/pacer/docket_report.py
juriscraper/pacer/rss_feeds.py
juriscraper/pacer/utils.py
tests/examples/pacer/rss_feeds/ca10.json
tests/examples/pacer/rss_feeds/ca10.xml
tests/examples/pacer/rss_feeds/ca11.json
tests/examples/pacer/rss_feeds/ca11.xml
tests/examples/pacer/rss_feeds/ca2_1.json
tests/examples/pacer/rss_feeds/ca2_1.xml
tests/examples/pacer/rss_feeds/ca4_1.json
tests/examples/pacer/rss_feeds/ca4_1.xml
tests/examples/pacer/rss_feeds/ca6.json
tests/examples/pacer/rss_feeds/ca6.xml
tests/examples/pacer/rss_feeds/cadc.json
tests/examples/pacer/rss_feeds/cadc.xml
tests/examples/pacer/rss_feeds/cafc.json
tests/examples/pacer/rss_feeds/cafc.xml
tests/local/test_PacerUtilTest.py

This PR adds support to query and parse appellate RSS Feeds.
Not too many differences between district and bankruptcy courts, the only ones are:
- No `pacer_case_id` in appellate RSS feeds.
- As in other sources, no `document_number` in appellate courts that don't have numbers yet.
- Appellate RSS Feeds use local timezones for the `date_filed`, this is a difference from district/bankruptcy courts that uses GMT, so added support to parse properly date-times for all the US timezones.

646 Added support to parse appellate RSS Feeds

---

juriscraper/pacer/rss_feeds.py
juriscraper/pacer/utils.py
tests/local/test_PacerUtilTest.py

As described in [#2091](https://github.com/freelawproject/courtlistener/issues/2091) reviewing the performance of parsing RSS feeds we got the following results when parsing an 800KB RSS file that contains approx. 810 entries:
* Actual parsing time: `0.30570292472839355` seconds
* Generate data dict: `2.520118236541748` seconds
The process that took the most time when generating the data dictionary was using `dateparser` for parsing the feed `datetime`.
Comparing this to using `dateutil.parser` and passing a dictionary of `tzinfos`, it only takes `0.6627788543701172` seconds to generate the dictionary for the same RSS file.
This significant difference can save many days when parsing millions of files. Therefore, I believe that it is worth using `dateutil` instead of `dateparser` for this …

Improve performance of parsing RSS feeds

---

juriscraper/pacer/rss_feeds.py
tests/examples/pacer/rss_feeds/ca10.json
tests/examples/pacer/rss_feeds/ca11.json
tests/examples/pacer/rss_feeds/ca2_1.json
tests/examples/pacer/rss_feeds/ca4_1.json
tests/examples/pacer/rss_feeds/ca6.json
tests/examples/pacer/rss_feeds/cadc.json
tests/examples/pacer/rss_feeds/cafc.json

While working on Troller BK and adding docket entries in bulk, I noticed that parsed appellate RSS entries do not contain the `pacer_seq_no`. Although it cannot be retrieved from appellate RSS feeds, I believe it's worth including the key in the JSON even if it is set to null, so that district/bankr feeds and appellate feeds contain the same fields.
I didn't notice this issue before because the `add_docket_entries` function in CL does not require the `pacer_seq_no` key, as it retrieves the value from the dict using `get()`. However, now when adding entries in bulk, I noticed the issue since the adding approach has changed.

Added null pacer_seq_no to appellate RSS feed entries

---

CHANGES.md
juriscraper/pacer/claims_activity.py
setup.py

Querying a Claims activity report for `insb` using the POST wildcard param `1-L_1_0-1` throws a 500 error.
The valid param for `insb` has the shape `148849513586046-L_945_0-1`, seems there's no wildcard (at least not evident) like `1-L_945_0-1` that works. 
So using a pre-generated param seems to work at least temporarily since it seems to expire or might be linked to the PACER session.
I also checked all the courts in order to find others that don't use `1-L_1_0-1` but seems that `insb` is the only one using a different param.

Claims activity POST request param wildcard for insb

---

juriscraper/pacer/rss_feeds.py
tests/examples/pacer/rss_feeds/nyed_1.json
tests/examples/pacer/rss_feeds/sdny_1.json

According to our plan in https://github.com/freelawproject/bigcases2/issues/87
This PR sorts the short descriptions of multiple RSS events alphabetically. This ensures that if the order of these entries in the RSS file changes the merged entry description will remain the same, so we'll be able to identify it instead of creating a new one in RECAP.

Sort multi RSS event entries short descriptions alphabetically

---

juriscraper/pacer/reports.py

This PR fixes #663 
It's a simple solution that adds the parameter `use_magic=1` to the free look download request in order to bypass the Free Look confirmation page.
This only works for district and bankruptcy notifications, since the appellate uses a different magic link format, and we don't have any examples (I looked for NDAs from the user that reported this issue, but found none) to see if there is a similar confirmation page for appellate magic links or not. So, we would need to know an NDA user that has this setting available to look for an example.
I tested this locally using magic links with this setting that were not used (due to the issue), and it worked properly. The confirmation page is bypassed, and the document is downloaded.

663 Bypass free look confirmation page.

---

juriscraper/pacer/list_of_creditors.py

I have divided the query method into two separate methods: `query_post_param` and `query`.
The first method, `query_post_param`, makes a GET request to obtain a valid POST parameter` x-L_1_0-1`. The second method, `query`, performs the actual POST request using the parameter returned by the previous method.
By doing this, we can safely retry the Celery task in CL if the `query_post_param` fails.

Split list of creditors query

---

.github/workflows/tests.yml
juriscraper/lib/html_utils.py
requirements.txt
setup.py
tests/examples/opinions/united_states/nh_example_4.compare.json

The cchardet package doesn't properly support python 3.11.

Replace unmaintained cchardet with charset-normalizer

---

requirements.txt

Lets update these to their latest versions.

Update version pinned dependencies

---

juriscraper/pacer/docket_report.py
tests/examples/pacer/dockets/district/alnb_1.html
tests/examples/pacer/dockets/district/alnb_1.json
tests/examples/pacer/dockets/district/dcd_3.html
tests/examples/pacer/dockets/district/dcd_3.json

This PR fixes the issue described in #687.
When the "View multiple documents" option is enabled on PACER, the docket entries table contains an extra column with a checkbox input to select the displayed documents.
Previously, this extra cell was removed when the checkbox was present within the cell. However, the problem arose when there was no checkbox in this extra cell, such as with sealed documents or entries without an attached document. As a result, the cell was not removed, causing a parsing mismatch.
A similar issue occurred with bankruptcy dockets, where there is an extra empty cell before the entry number. As a result, the entry number was incorrectly placed in the description field, while the entry number itself remained null.
To resolve the problem, the "View multiple documents" …

687 Fix docket report parsing on view multiple documents layout

---

juriscraper/pacer/docket_report.py
tests/examples/pacer/claims_activity/insb_1.json
tests/examples/pacer/claims_registers/insb.json
tests/examples/pacer/dockets/bankruptcy/insb_1.html
tests/examples/pacer/dockets/bankruptcy/insb_1.json
tests/examples/pacer/dockets/bankruptcy/insb_2.html
tests/examples/pacer/dockets/bankruptcy/insb_2.json

This PR fixes #690 
The problem is that in some INSB bankruptcy dockets the docket number has the following format:
`17-90266-BHL-13`
Which was being parsed as: `66-BHL-13`
To parse bankruptcy docket numbers it can be used `docket_number_dist_regex` or `docket_number_bankr_regex` since both formats can be available in bankruptcy dockets.
The problem was that `docket_number_dist_regex` `((\d{1,2}:)?\d\d-[a-zA-Z]{1,4}-\d{1,10})` was matching `17-90266-BHL-13` as `66-BHL-13`.
To solve it I added a negative look-behind `(?<!\d)` so if the char before the first two digits is also a digit, then it's not matched.
So in this case `17-90266-BHL-13` is ignored by `docket_number_dist_regex`, so that solves the issue.
In addition by doing some testing, I also found that the …

690 Fix bankruptcy docket number parsing

---

juriscraper/pacer/case_query.py
tests/examples/pacer/case_queries/insb_1.html
tests/examples/pacer/case_queries/insb_1.json
tests/examples/pacer/case_queries/insb_2.html
tests/examples/pacer/case_queries/insb_2.json
tests/examples/pacer/case_queries/scb_1.html
tests/examples/pacer/case_queries/scb_1.json

This PR solves the issue described in https://github.com/freelawproject/courtlistener/issues/2819 regarding the unparsed judge's name in SCB, as well as the issue detailed in  https://github.com/freelawproject/courtlistener/discussions/2820 about the case name not being parsed in INSB.
Both issues were related to iquery pages for these two courts, which had different formats.
- In the case of SCB, the judge's name was indeed parsed, but was added under the key `chief_judge` instead of `assigned_to_str` so it was not being recognized and assigned in Courtlistener. So I changed the key name to `assigned_to_str`.
- In INSB, the case name is within a `font` tag. So I added a new parsing method to properly handle this case.

2819 Fix insb and scb iquery pages parser

---

.github/dependabot.yml

In theory, this will make updates easier keep up with. Given aggressiveness of deprecation in Github actions - that would break CI/CD - keeping up to date has more than passing importance.

feat(deps): configure Dependabot for Github actions

---

juriscraper/pacer/docket_report.py

This doesn't seem to actually indicate a docket report is invalid.

Try to parse pages with unable to create PDF file error

---

juriscraper/pacer/appellate_docket.py

.decode() not work in python3, whoops.
The problem is such:
```
(juriscraper) jhawk@lrr juriscraper % python3 -m juriscraper.pacer.appellate_docket /dev/null
Warning: No such file or directory: /var/log/juriscraper/debug.log. Have you created the directory for the log?
Juriscraper will continue to run, and all logs will be sent to stderr.
<frozen runpy>:128: RuntimeWarning: 'juriscraper.pacer.appellate_docket' found in sys.modules after import of package 'juriscraper.pacer', but prior to execution of 'juriscraper.pacer.appellate_docket'; this may result in unpredictable behaviour
Parsing HTML file at /dev/null
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File …
```

appellate_docket.py: remove .decode() python2ism

---

juriscraper/pacer/utils.py

Collision examples:
https://www.courtlistener.com/docket/7625727/michael-p-long-v-robert-l-wilkie/
https://www.courtlistener.com/docket/67393008/people-for-the-ethical-treatment-of-animals-v-lawrence-tabak/

Handle cadc/cavc docid prefix collision

---

juriscraper/lib/test_utils.py

It's not OK to print
juriscraper.lib.exceptions.SlownessException: This scraper took 3.372174024581909s to test, which is more than the allowed speed of 1s. Please speed it up for tests to pass.
Limit to three digits of precision to the right of the decimal point (fixed-point).

test_utils.py/warn_or_crash_slow_parser() significant figures

---

setup.cfg

(juriscraper) jhawk@lrr juriscraper % python3 setup.py test --help /opt/homebrew/lib/python3.11/site-packages/setuptools/dist.py:744: SetuptoolsDeprecationWarning: Invalid dash-separated options !!
********************************************************************************
Usage of dash-separated 'description-file' will not be supported in future
versions. Please use the underscore name 'description_file' instead.
This deprecation is overdue, please update your project and remove deprecated
calls to avoid build errors in the future.
See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
********************************************************************************
!!

setup.cfg: description_file not description-file

---

tests/local/test_DocketParseTest.py

Don't print `anon_text` to save test output from thousands of lines of HTML that clutters it.

test_DocketParseText.py: assert_anonymized() cleanup spew

---

juriscraper/opinions/united_states/state/coloctapp.py

issue #758 
refactored by changing regex pattern. was hardcoded for 2022, so it didn't pick up any 2023 cases. 
new pattern is `202\d{1}` so it picks up any cases 2020-2029.
some technical debt: will need to be changed in 2030.
This PR does not address the fact that the test examples only have cases from 2022. A more rigorous test would check 2023 examples, or maybe even examples from different years.
I also don't know if this fix completely addresses the issue and fixes the scraper. At the very least it should be able to pick up cases from the announcement PDF on the court website.
I've suggested a few regex patterns, but decided on one generalized for this decade 2020-2029.
* The narrow scope limits unintended consequences while still being good for cases until 2029.
* It also lets us …

Refactor regex pattern in coloctapp to get cases from any year 2020-2029

---

juriscraper/opinions/united_states/state/conn.py
juriscraper/opinions/united_states/state/connappct.py
tests/examples/opinions/united_states/connappct_example.compare.json
tests/examples/opinions/united_states/connappct_example.html

feat(connappct): Fix Conn App Ct

---

juriscraper/pacer/docket_report.py

It would appear looking for the `view_multi_docs` form name is more reliable.

Improve reliability of View multiple documents detection

---

README.rst

Tiny link adjustments - the Selenium standalone-firefox-debug image link is deprecated in favor of standalone-firefox, the Black editor integration page was renamed, and the pre-commit link had markdown issues.

Fix broken/deprecated links in README.rst

---

juriscraper/opinions/united_states/federal_bankruptcy/bap1.py
tests/local/test_ScraperExtractFromTextTest.py

Bap1 format for date_filed was a string
but CL is expecting it as a datetime.date
object
Also - Updated tests to reflect this change.

fix(bap1): Update bap1

---

juriscraper/lib/html_utils.py
requirements.txt

The lxml project [recommends](https://lxml.de/lxmlhtml.html#cleaning-up-html) replacing clean functionality with [nh3](https://nh3.readthedocs.io/). This should hopefully also improve performance.

Replace lxml based sanitizers with nh3

---

juriscraper/opinions/united_states/federal_appellate/cadc_pi.py

Error was surfacing on Courtlistener when trying to get the download_url of scraped items
Problem was a duplication of https protocol inserted on parsing code `https:https://`
This was useful in the past, causing errors now. Still, code is adapted in case it changes back to the old format
Solves: #817

fix(cadc_pi): Fixed InvalidURL error

---

juriscraper/pacer/email.py

Ensure that document_number field dies not have "doc" value since this will cause an error on DocketEntry queries
Solves #799

fix(pacer.email): validate document_number in _get_docket_entries

---

juriscraper/pacer/claims_register.py
juriscraper/pacer/docket_report.py
tests/examples/pacer/claims_registers/ilnb.html
tests/examples/pacer/claims_registers/ilnb.json
tests/examples/pacer/claims_registers/pamb.html
tests/examples/pacer/claims_registers/pamb.json

Solves #855
- Added extra `b` tag condition to XPATH to solve original Sentry Issue.
- Added field_mappings honorable_judge that maps to assigned_to_str
- Added field_mappings chief_judge that maps to assigned_to_str
- Modified `_get_label_value_pair` to clean whitespace and newlines from label. date_entered was returning with multiwhitespace and newlines inside
- added 2 test cases to catch judge and date entered requirements

fix(pacer.claims_register): fix IndexError in report.metadata

---

juriscraper/AbstractSite.py
juriscraper/lib/network_utils.py
juriscraper/opinions/united_states_backscrapers/federal_appellate/cadc.py

Resolves underlying issue in #819 
Add custom adapter to abstract site
update adapter in network utils
Remove it from CADC where it is unused

feat(network_utils): Update SSL Adapter

---

juriscraper/opinions/united_states/state/haw.py

Solves: #871
Problem was a result row for hawapp where the docket cell had no <a> tag, causing an IndexError

fix(hawapp): skip record if docket cell has no <a> tag

---

juriscraper/pacer/email.py
tests/examples/pacer/nef/s3/dcb_1.json
tests/examples/pacer/nef/s3/dcb_1.txt
tests/examples/pacer/nef/s3/dcb_2.json
tests/examples/pacer/nef/s3/dcb_2.txt
tests/examples/pacer/nef/s3/ianb.json
tests/examples/pacer/nef/s3/ianb.txt
tests/examples/pacer/nef/s3/ndb_1.json
tests/examples/pacer/nef/s3/ndb_1.txt
tests/examples/pacer/nef/s3/paeb_1.json
tests/examples/pacer/nef/s3/paeb_1.txt
tests/examples/pacer/nef/s3/paeb_2.json
tests/examples/pacer/nef/s3/paeb_2.txt
tests/examples/pacer/nef/s3/paeb_3.json
tests/examples/pacer/nef/s3/paeb_3.txt
tests/examples/pacer/nef/s3/vaeb_1.json
tests/examples/pacer/nef/s3/vaeb_1.txt

Solves #912
Add parsing clauses and test cases for:
- dcb
- ndb
- ianb
- paeb
- vaeb
Note that some tests will have no short description
- dcb_1: no short description available
- paeb_3: is multidocket NEF, currently unsupported
Fixes COURTLISTENER-6HH
Fixes COURTLISTENER-6HH
Fixes COURTLISTENER-6HR
Fixes COURTLISTENER-6HS
Fixes COURTLISTENER-6J7

fix(pacer.email): _parse_bankruptcy_short_description

---

CHANGES.md
juriscraper/pacer/download_confirmation_page.py
juriscraper/pacer/http.py

This PR updates the `DownloadConfirmationPage` class to reduce the read timeout of the `GET` request within the `query` method. These changes align with the retry strategy improvements(exponential task retries with relatively fast timeouts) discussed in [courtlistener#3766](https://github.com/freelawproject/courtlistener/issues/3766) for `process_recap_email` task.

feat(pacer): Tweak the DownloadConfirmationPage class to set smaller timeout

---

CHANGES.md
juriscraper/pacer/reports.py

This PR adds a new method to the `BaseReport` class. This helper uses the content of the receipt page to flag potentially sealed docket entries.

feat(base report): Adds a method for checking sealed status on a entry

---

juriscraper/AbstractSite.py
juriscraper/opinions/united_states/state/tex.py
sample_caller.py

feat(backscrape): support dynamic backscraping ranges
feat(tex): support dynamic backscraping in tex
Support passing optional start and end backscraping values.
This will help localize backscrapes without having to change
harcoded values. However, it will have to be implemented
on a source by source basis, since the ranges are created
with full dates, years, indexes, etc.
This PR also implements the dynamic backscraper for `tex`
which is one of the sources where we have the biggest gaps
Solves #942: dynamic backscraping
Solves #944: implement `tex` backscraping
but will need a complimentary PR in courtlistener to deploy
Test with:
```
python sample_caller.py -c juriscraper.opinions.united_states.state.tex --backscrape --backscrape-start=01/01/2018 --backscrape-end=01/01/2019
python …
```

feat(backscrape): support dynamic backscraping ranges

---

juriscraper/opinions/united_states/state/texag.py
tests/examples/opinions/united_states/texag_example.compare.json

download_url xpath was picking an HTML page instead of the PDF link, causing incorrect downloads and duplicates. To correct past corrupt data a backscraper will be needed
Solves #940

fix(texag): correct content type and link xpath

---

juriscraper/pacer/email.py
tests/examples/pacer/nef/s3/deb_2.json
tests/examples/pacer/nef/s3/pamb_1.json
tests/examples/pacer/nef/s3/pamb_1.txt
tests/examples/pacer/nef/s3/pamb_2.json
tests/examples/pacer/nef/s3/pamb_2.txt
tests/examples/pacer/nef/s3/pamb_3.json
tests/examples/pacer/nef/s3/pamb_3.txt

Helps solve #912
- Found a 18 character limit for the case_name on the subject. This also applies to the`deb_2.txt` example file
- Found that case names with " and " that separates a couple use the first person's name in the subject
Tested this against a 100 recap.emails reported on Sentry. Other instances of the "and" separator (for each case, each row is: file id, subject, case_name, extracted short_description):
```
90 pamb kd7gqbjvshbvavddtgi8dd6shlmdulj7kqd0ido1
Ch-13 1:22-bk-02406-HWV -Roger Dale Moore Motion to Modify Plan
Roger Dale Moore and Barbara Anne Moore
Motion to Modify Plan
========
83 pamb a4rslhlor0j8flmrhoa4vo7g82gh53670uljg1g1
Ch-13 1:22-bk-02406-HWV -Roger Dale Moore  Hearing Continued
Roger Dale Moore and Barbara Anne Moore
Hearing Continued
========
84 pamb …
```

fix(pacer.email): parse short description for `pamb`

---

juriscraper/opinions/united_states/state/nj.py

Fixes #1044 by using partition instead of split. Partition returns the part before the separator, the separator itself, and the part after the separator. If the separator isn't found, the first element of the tuple will be the whole string, and the other two will be empty strings.
Not exactly sure on the process of adding a test to test_ScraperExtractFromTextTest.py so would appreciate some guidance there as this is my PR here.

Changes nj.py opinion scraper to fix #1044 

---

juriscraper/opinions/united_states/state/nj.py
juriscraper/opinions/united_states/state/njsuperctappdiv_p.py
juriscraper/opinions/united_states/state/njsuperctappdiv_u.py
juriscraper/opinions/united_states/state/njtaxct_p.py
juriscraper/opinions/united_states/state/njtaxct_u.py

Helps solve #929
- Backscraper in nj can also be used in inheriting scrapers: njtaxct_u, njtaxct_p, njsuperctappdiv_p, njsuperctappdiv_u
- Tweak HTML parsing to skip cases with no links, and cases where name is inside a span instead of anchor tag

feat(nj): implement backscraper

---

juriscraper/opinions/united_states/state/ri.py

Fix RI scraper
Return an empty string instead of none for summaries.

feat(ri): Fix summary

---

juriscraper/pacer/email.py
tests/examples/pacer/nef/s3/nhb_1.json
tests/examples/pacer/nef/s3/nhb_1.txt
tests/examples/pacer/nef/s3/tnmb_1.json
tests/examples/pacer/nef/s3/tnmb_1.txt

Related to #912
Handle short description parsing in _parse_bankruptcy_short_description for nhb and tnmb

fix(recap.email): parse short description for nhb and tnmb

---

juriscraper/lib/log_tools.py

Changed named from "Logger" to `__name__` or "juriscraper.lib.log_tools" This follows the hierarchical naming convention used by Python's logging configuration and helps understand logging config in Courtlistener
From freelawproject/courtlistener#4188

fix(log_tools): rename default logger

---

juriscraper/pacer/free_documents.py

This small change adds a new attribute to the FreeOpinionReport class, this new attribute returns a list of dicts, each dict contains the response but also the start and end date used to query pacer.
This is very helpful if we want to query a large date range, FreeOpinionReport processes in 7 days ranges and we want to save an html file for each date range, this will allow us to format the html files in a format like: `free_opinions_report_{court_id}_from_{start_date}_to_{end_date}.html`

Update free opinion report

---

juriscraper/opinions/united_states/state/oklaag.py

Fixes #1091
URL had been pointing to the `okla` site, incorrectly, since the last update to the Oklahoma sites

fix(oklaag): correct self.url

---

juriscraper/pacer/reports.py

This PR introduces a new optional argument, de_seq_num, to the download_pdf and _query_pdf_download methods. By providing a default value for this argument, potential conflicts with existing method implementations are mitigated.
Fixes #1088
After merging this PR; I'll create another one in CL to update the [process_recap_email](https://github.com/freelawproject/courtlistener/blob/723b7ec84101b18fa2f0aa0dcb7ef7788dc74361/cl/recap/tasks.py#L2451-L2668) task.

feat(pacer): Adds the de_seq_num to the download method

---

juriscraper/opinions/united_states/state/ny.py
juriscraper/opinions/united_states/state/nyappdiv_1st.py
juriscraper/opinions/united_states/state/nyappterm_1st.py
juriscraper/opinions/united_states/state/nytrial.py

Fixes #1042
Add a function to set the required api token in both headers objects used in Juriscraper / Courtlistener. For this to work, we will need to modify CL to use the headers for ny courts.
Use that function on ny, nyappdiv, nyappterm, nytrial, which are base classes for more scrapers

fix(ny, nyappdiv, nyappterm, nytrial): add X-Api-Token header

---

juriscraper/opinions/united_states/state/massappct_u.py
sample_caller.py

FIxes #1103
Also, add v_print to the sample_caller binaries download, for easier debugging

fix(massappct_u): no longer uses mass headers

---

juriscraper/AbstractSite.py
juriscraper/opinions/united_states/state/mass.py
juriscraper/opinions/united_states/state/massappct_u.py
juriscraper/opinions/united_states/state/ny.py
sample_caller.py

Related to freelawproject/courtlistener#4281
- Update sample caller to reflect Courtlistener's get_binary_content behaviour
- get rid of self.headers, which was a copy of self.request["headers"] wherever it was used
- add a flag `needs_special_headers` for the caller to know it has to use the self.request["headers"]
- simplify `mass` headers, the only thing needed was the changed user-agent
- minn is not working, will leave it as is and fix it in another issue
- Updated NY api key header name following latest email
- removed massappct_u self.headers, since the site has no special headers requirements

refactor(mass, ny, sample_caller): add flag site.needs_special_headers

---

juriscraper/pacer/docket_report.py

```
Court: District of New Jersey
Case Number:	2:23-cv-01194
Pacer CaseID:	509180	
Court Code: njd
```
For this case docket report page has different format.
This difference causes Index out of range error because function expects `Date Filed` instead of `Filed Date`. 
Added `Filed Date` as alternative to `xpath()` method

Fixed IndexOutOfRange error in DocketReport::_set_metadata_values method

---

juriscraper/pacer/internet_archive.py
tests/examples/pacer/dockets_internet_archive/almd_49523.json
tests/examples/pacer/dockets_internet_archive/azd_1061043.json
tests/examples/pacer/dockets_internet_archive/azd_318008.json
tests/examples/pacer/dockets_internet_archive/cacb_1669936.json
tests/examples/pacer/dockets_internet_archive/cand_194617.json
tests/examples/pacer/dockets_internet_archive/cand_287492.json
tests/examples/pacer/dockets_internet_archive/dcd_119997.json
tests/examples/pacer/dockets_internet_archive/flmd_330522.json
tests/examples/pacer/dockets_internet_archive/nysd_476194.json
tests/examples/pacer/dockets_internet_archive/ohsd_170541.json
tests/examples/pacer/dockets_internet_archive/txnd_202294.json
tests/examples/pacer/dockets_internet_archive/utd_103577.json

Attachments should not have `short_description` keys but rather just a `description` key. Also remove redundant `document_number` and `date_filed` keys from attachments.

Fix IA attachment description keys

---

README.rst

√  Support opinions from for all intermediate appellate state courts
The caveat is ND has a IAC but hasnt issued
an opinion for 17 years and would be
published with the supreme court opinions

docs(readme): Update future goals

---

sample_caller.py

Also, move logger behavior to inside `main`, to avoid modifying the logger when not calling the sample_caller, for example, from Courtlistener

fix(sample_caller): binaries was left undefined

---

juriscraper/opinions/united_states/state/sc.py

Related to  #1189
Opinions from terms older than 2012-06 are in HTML format, which needs updating the
self.expected_content_types attribute.
This happens both in `sc` and `scctapp`

fix(sc): add HTML expected_content_type for backscrapers

---

juriscraper/AbstractSite.py

fix(AbstractSite): put cache-control key inside headers dict
Solves #1110
cache-control key was not in the proper place, so it didn't do 
anything. Also, update the header value.
Adds `Pragma` header with 'no-cache' value for older caches

fix(AbstractSite): put cache-control key inside headers dict

---

juriscraper/opinions/united_states/state/coloctapp.py

Solves:
https://github.com/freelawproject/juriscraper/issues/1215
We are getting duplicate hashes again due to some documents having multiple hash altering elements. Generalize cleanup_content to cases with more than one element

fix(coloctapp): update cleanup_content

---

juriscraper/opinions/united_states/state/okla.py

Improves HTML cleanup for Oklahoma Opinions.

feat(okla): Improve Okla HTML cleanup

---

juriscraper/pacer/reports.py

While debugging another issue in the `recap-fetch` API, I noticed that our code was incorrectly identifying certain sealed documents on PACER. This led to a misleading error message being added to the fetch queue:
> Unable to download PDF. PDF not served as binary data and unable to find iframe src attribute. URL: https://ecf.caed.uscourts.gov/doc1/03319001890, caseid: 300601, magic_num: None. court_id='caed'
To address this issue, I've added a new phrase to the sealed document check logic and refactored the if statement
Here's another example of a sealed document: https://ecf.vawd.uscourts.gov/doc1/19111488805

feat(pacer): Updates logic to create error message.

---

juriscraper/opinions/united_states/state/mass.py

The encoding cause an issue when uploading
html to aws.  Decode html should fix this

feat(mass): Fix cleanup content file

---

juriscraper/opinions/united_states/state/ky.py

Solves https://github.com/freelawproject/juriscraper/issues/1151
Date range of 30 days for regular scraper made the page return stale results; even when not exceeding the page size limit. Using a smaller range returns current results
Also, refactor disposition parsing to exclude placeholder values

fix(ky): make date range smaller

---

juriscraper/opinions/united_states/state/sc.py
tests/local/test_ScraperExtractFromTextTest.py

Solves https://github.com/freelawproject/juriscraper/issues/1188
The value we were previously collecting as a docket number was a sort of document ID

feat(sc): use extract_from_text to get docket_number

---

juriscraper/OpinionSite.py
juriscraper/opinions/united_states/state/nd.py
juriscraper/opinions/united_states/state/nytrial.py
juriscraper/opinions/united_states/state/pasuperct.py
juriscraper/opinions/united_states/state/vt.py
juriscraper/opinions/united_states/state/wis.py
juriscraper/opinions/united_states/state/wisctapp.py
tests/local/test_ScraperExtractFromTextTest.py

Solves #1297
We will use eyecite on Courtlistener's site to parse and validate the citation string

fix(extract_from_text): now returns a plain citation string

---

CHANGES.md
juriscraper/pacer/appellate_docket.py

This PR fixes inconsistency in `download_pdf` behavior for `AppellateDocketReport` class
While working on https://github.com/freelawproject/courtlistener/issues/3877,  I found that the return type of `download_pdf` method in the `AppellateDocketReport` class is different from what's documented in the [changes.md](https://github.com/freelawproject/juriscraper/blob/dde9d687c6c1051585c03d3baf8c6b27b81a0898/CHANGES.md) file.
This PR fixes that so it behaves the same as the `download_pdf` method from the `BaseReport` class. 
This change makes it easier to use both `AppellateDocketReport` alongside other classes that inherit from `BaseReport` without needing any special workarounds.

fix(appellate): Corrects download_pdf return type

---

.github/workflows/pypi.yml
CHANGES.md
setup.py

also, fixes pypi github action #1308

version bump v2.6.54

---

juriscraper/pacer/appellate_docket.py

This PR improves the `download_pdf` method to handle cases where attachment pages are returned instead of the expected PDF documents.

feat(appellate): Handle Attachment Pages in download_pdf

---

juriscraper/pacer/appellate_docket.py
tests/examples/pacer/dockets/appellate/ca5_212643.html
tests/examples/pacer/dockets/appellate/ca5_212643.json

Fixes: #915 
This PR adds support for parsing `docket_numbers` wrapped in a tel: href tag in appellate dockets.
Besides the docket_number parsing, I noticed in the example added that it doesn't have an `Ordering Judge`, but it does have an `Originating Judge`, which we are currently not parsing. Is it the same as an `Ordering Judge`, or is it ok to just ignore it?

915 Added support for parsing docket numbers wrapped in a tel: href in the appellate docket report

---

CHANGES.md
juriscraper/opinions/united_states/state/ny.py
juriscraper/opinions/united_states/state/nytrial.py

Fixes #1393
Affects `ny`, `nytrial`, `nyappdiv` and `nyappterm` scrapers

feat(ny): implement `cleanup_content` to delete timestamps

---

CHANGES.md
juriscraper/opinions/united_states/state/nytrial.py

Add Bearer Token for NY Trial Courts. 
Fixes https://github.com/freelawproject/juriscraper/issues/1396

fix(nytrial): Add token auth

---

CHANGES.md
juriscraper/opinions/united_states/administrative_agency/asbca.py

This pull request addresses improvements to the `asbca` scraper functionality and updates the changelog accordingly. The most important changes include fixing the scraper to use special headers and documenting the fix in `CHANGES.md`.
* [`juriscraper/opinions/united_states/administrative_agency/asbca.py`](diffhunk://#diff-a453b57c8b25c47f1b10b35a84ce2fdc975485febc46951c7d65e3bb453482ebR39): Added the `needs_special_headers` attribute to ensure the scraper uses special headers, improving its functionality.
* [`CHANGES.md`](diffhunk://#diff-d975bf659606195d2165918f93e1cf680ef68ea3c9cab994f033705fea8238b2R25): Added a note under "Fixes" to document the update to the `asbca` scraper, specifying the use of special headers.

Issue asbca scraper not working 1411

---

CHANGES.md
juriscraper/opinions/united_states/federal_bankruptcy/bap1.py

This pull request addresses two main areas: bug fixes and code cleanup. It includes a fix for the `bap1` scraper to ensure it properly retrieves recent data.
* [`CHANGES.md`](diffhunk://#diff-d975bf659606195d2165918f93e1cf680ef68ea3c9cab994f033705fea8238b2L21-R21): Added a note about fixing the `bap1` scraper to ensure it correctly scrapes recent data.
* [`juriscraper/opinions/united_states/federal_bankruptcy/bap1.py`](diffhunk://#diff-81fb06141c4e06a63993df9dff3584c4ffe9533af6584c549fcd31fa7383a9ecL51-L66): The `_download` method was removed because it was looking at the last page instead of the main page where all the current opinions are located.
* [`juriscraper/opinions/united_states/federal_bankruptcy/bap1.py`](diffhunk://#diff-81fb06141c4e06a63993df9dff3584c4ffe9533af6584c549fcd31fa7 …

fix(bap1): remove _download method from scraper

---

CHANGES.md
juriscraper/opinions/united_states/state/va.py
tests/examples/opinions/united_states/va_example.compare.json

This pull request addresses issues with incorrect docket number values in the Virginia scraper and improves code clarity and functionality. Updates include fixing the extraction logic for docket numbers, enhancing the `_process_html` method with a docstring, and adjusting test cases to reflect the corrected docket number format.
* [`juriscraper/opinions/united_states/state/va.py`](diffhunk://#diff-e095b253ebe5ca72f07677837f76543d4ae5490ea6079d140b1f5c2ae8ef0cdcL36-R40): Updated the `_process_html` method to correct the logic for extracting docket numbers, ensuring the proper value is retrieved from the HTML content.
* [`juriscraper/opinions/united_states/state/va.py`](diffhunk://#diff-e095b253ebe5ca72f07677837f76543d4ae5490ea6079d140b1f5c2ae8ef0cdcL13-R17): Added a docstring to the …

Issue collecting bad docket number values for va 1441

---

CHANGES.md
juriscraper/pacer/__init__.py
juriscraper/pacer/hidden_api.py
juriscraper/pacer/http.py
tests/network/test_PacerAuthTest.py

Key changes: 
- **Integrated ACMS Authentication in `PacerSession`:**
- **Centralized Authentication Logic**: `PacerSession` now handles ACMS authentication directly, leveraging its existing session management capabilities.
- **Automatic Bearer Token Handling**: `PacerSession` is enhanced to automatically include the necessary ACMS bearer tokens in request headers when an ACMS-specific request is identified.
- **Court-Specific ACMS Token Management**: The `PacerSession` class now includes an `acms_tokens` attribute which maps `court_id`s to its respective ACMS authentication token. ( While working on this PR, I noticed that ACMS tokens are valid only for a single court)
- **New `AcmsCaseSearch` Class**: Introduces `AcmsCaseSearch`, a dedicated class for programmatically looking up ACMS …

feat(acms): Adds ACMS authentication support to PacerSession 

---

CHANGES.md
juriscraper/pacer/docket_report.py
tests/examples/pacer/case_queries/ared_147425.html
tests/examples/pacer/case_queries/ared_147425.json

The `docket_number_dist_regex` was updated to support parsing case types with up to five letters, e.g: `4:25-crcor-00029`

1465 Tweaked docket_number_dist_regex regex

---

CHANGES.md
juriscraper/opinions/united_states/state/minn.py

This pull request modifies the `Site` class in `juriscraper/opinions/united_states/state/minn.py` to adjust the handling of the `needs_special_headers` attribute.

fix(minn): restore needs_special_headers flag in scraper initialization

---

CHANGES.md
juriscraper/lib/network_utils.py
juriscraper/pacer/acms_attachment_page.py
tests/network/test_PacerAcmsAttachmentPageTest.py

key changes: 
- Adds the `query` method to `ACMSAttachmentPage` to enable data retrieval.
- Updates `AcmsApiClient` to introduce a helper method to fetch and maps attachments for a specific docket entry.
depends on #1466

feat(acms): Adds logic for attachment retrieval in ACMSAttachmentPage

---

CHANGES.md
juriscraper/opinions/united_states/territories/visuper_p.py

This pull request addresses a bug fix and updates the scraper for the Superior Court of the Virgin Islands (`visuper_p.py`). The changes ensure compatibility with updated HTML tags and improve documentation for historical updates to the scraper.

fix(visuper_p): update adaptation to new HTML tags in scraper

---

CHANGES.md
juriscraper/pacer/http.py

The existing regex only matched URLs starting with https. This PR updates the pattern to also match http, improving compatibility with environments that may not enforce HTTPS (like our proxy). The change preserves `court_id` extraction.

feat(pacer): Tweaks ACMS regex to support http in addition to https

---

CHANGES.md
juriscraper/pacer/acms_attachment_page.py

This PR adds a check to ensure ACMS user data is loaded before querying attachment pages. Since ACMS attachment  requests require user-specific authentication data in their `body`, this change verifies that the session includes the necessary ACMS credentials and loads them if missing.

feat(pacer): Ensure ACMS user data is loaded before fetching attachments

---

CHANGES.md
juriscraper/oral_args/united_states/federal_appellate/ca9.py
tests/examples/oral_args/united_states/ca9_example.compare.json

This pull request addresses updates to the `ca9` scraper and fixes download URL formatting issues for oral argument recordings.
this PR addresses -- #1515

update download URLs to point to the correct media datastore

---

CHANGES.md
juriscraper/opinions/united_states/state/colo.py
juriscraper/opinions/united_states/state/coloctapp.py

Implement the cleanup_content() method in `colo` scraper to:
- Force proper HTML structure
- Ensures python-magic always detects HTML
- Allows using strip_bad_html_tags_insecure() from juriscraper to remove unwanted elements
- Maintains content integrity while standardizing output
- It also implements cleanup_content method in `coloctapp` to return raw pdf content
I used these query to detect bad opinions from `colo` and `coloctapp`, we need to remove them and run the backscraper:
Colo:
```
SELECT 
"search_opinion"."id", 
"search_opinion"."cluster_id", 
"search_opinion"."download_url", 
"search_opinion"."local_path", 
"search_opinioncluster"."date_filed",
"search_opinioncluster"."case_name"
FROM "search_opinion" 
INNER JOIN "search_opinioncluster" ON ("search_opinion"."cluster_id" = …
```

fix(colo): Wrap content in html structure

---

CHANGES.md
juriscraper/lib/network_utils.py
juriscraper/pacer/acms_docket.py

This PR introduces support for requesting PDFs from the ACMS court API and adds helper methods to validate and retrieve files.
**Key changes:** 
- `AcmsApiClient.download_pdf`:
- Initiates a PDF merge request with the court API.
- Polls the status until completion.
- Retrieves and returns the merged PDF.
- `ACMSDocketReport.download_pdf`:
- Retrieves document list for a given entry.
- Handles cases where no document is returned by the API.
- Handle cases when no `doc_id` is provided and the API returns multiple documents.
- Checks that a provided `doc_id` exists in the entry before downloading.
- Downloads the selected document via the API.
----
My initial assumption was that we could handle download requests with just the data we store in CourtListener. It turns out that the court API …

feat(acms): implements PDF download method

---

CHANGES.md
juriscraper/opinions/united_states/state/sd.py
tests/local/test_ScraperExtractFromTextTest.py

This pull request enhances the South Dakota (`sd`) scraper by adding extraction of lower court information from opinion text.

feat(sd): extract lower court information from scraped text

---

CHANGES.md
juriscraper/opinions/united_states/state/utah.py
juriscraper/opinions/united_states/state/utahctapp.py
tests/local/test_ScraperExtractFromTextTest.py

This pull request enhances the Utah state opinions scraper by adding functionality to extract lower court information from opinion text.

feat(utah): add lower court extraction functionality for Utah opinions

---

CHANGES.md
juriscraper/opinions/united_states/state/dc.py
tests/local/test_ScraperExtractFromTextTest.py

This pull request updates the DC state court scraper to retrieve lower court information.
this PR addresses in part -- #1590

feat(dc): implement lower court extraction from scraped text

---

CHANGES.md
juriscraper/opinions/united_states/state/iowa.py
tests/local/test_ScraperExtractFromTextTest.py

This pull request adds lower court extraction functionality to the Iowa scrapers.

feat(iowa): add lower court extraction functionality to Iowa scrapers

---

CHANGES.md
juriscraper/opinions/united_states/state/ky.py
tests/local/test_ScraperExtractFromTextTest.py

This pull request adds support for extracting lower court information from Kentucky (`ky`)

feat(ky): add extract_from_text method to retrieve lower court information

---

CHANGES.md
juriscraper/opinions/united_states/state/mont.py
tests/local/test_ScraperExtractFromTextTest.py

This pull request adds support for extracting lower court information in the Montana (`mont`) scraper.

feat(mont): extract lower court information and enhance citation retrieval

---

CHANGES.md
juriscraper/opinions/united_states/state/nd.py
tests/local/test_ScraperExtractFromTextTest.py

This pull request adds support for extracting lower court information from North Dakota (`nd`) court opinions.

feat(nd): extract lower court information from text

---

CHANGES.md
pyproject.toml
uv.lock

This pull request updates the version of the `juriscraper` project to `2.6.91` and revises the changelog in `CHANGES.md` to reflect the latest changes and fixes.

chore: bump version to 2.6.91 and update CHANGELOG

---

CHANGES.md
sample_caller.py

This pull request addresses a bug in the `sample_caller.py` script by correcting the argument name used in a call to the `download_content` method. This change ensures that the function is called with the correct parameter, preventing potential runtime errors.
this PR addresses -- #1619

fix(sample_caller): rename parameter for clarity in download_content call
