opinions/united_states/state/fladistctapp_4.py

Needs code review whether this is a viable approach (self.html containing tuples)

Fixes Florida 4th District Court of Appeal scraper

---

opinions/united_states/state/wyo.py

Fixes Wyoming Supreme Court crawler

---

opinions/united_states/federal_district/ed_louisiana.py

Louisiana2

---

opinions/united_states/state/fladistctapp_5.py

Fixed logic to pull proper absolute path for PDF download links.  Simplified date logic by using our handy convert_date_string() function.

Fixed fladistctapp_5 pdf url logic

---

opinions/united_states/state/delaware.py
tests/examples/opinions/united_states/delaware_example.html
tests/examples/opinions/united_states/delctcompl_example.html

These scrapers were pulling no data, and the code seemed overly complex, so I simplified it.  I also updated the example files.

Fixing delaware scraper, which fixed delctcompl as well

---

opinions/united_states/administrative_agency/__init__.py
opinions/united_states/administrative_agency/asbca.py
opinions/united_states/federal_special/__init__.py
opinions/united_states/state/fladistctapp_4.py
tests/examples/opinions/united_states/asbca_example_2.html
tests/examples/opinions/united_states/fladistctapp_4_example_2.html

Includes fix to asbca scraper and new example file

 Re-enabling acca & asbca scrapers; fixing asbca & fladistctapp_4 scrapers

---

juriscraper/opinions/united_states/state/wyo.py
tests/examples/opinions/united_states/wyo_example.json

The json endpoint moved and was updated slightly.

Fixing wyo scraper

---

juriscraper/__init__.py
juriscraper/opinions/united_states/administrative_agency/bva.py
juriscraper/opinions/united_states/federal_appellate/cafc.py
juriscraper/opinions/united_states/state/colo.py
juriscraper/opinions/united_states/state/minn.py
tests/examples/opinions/united_states/cafc_example_2.html

Restructuring to handle table rows without a pdf link.  Adding new test file and bumping version.

Fixing cafc scraper

---

juriscraper/opinions/united_states/state/conn.py
tests/examples/opinions/united_states/conn_example_2.html

Site introduced new formatting inconsistency in how it presents it's dates.  Fixed scraper to handle that.  Added new test file as well.

Fixing conn scraper

---

juriscraper/opinions/united_states/state/ri_p.py
juriscraper/opinions/united_states/state/ri_u.py
tests/examples/opinions/united_states/ri_p_example_3.html

Restructured ri_p to be more intuitive and hopefully a little more stable in its handling or the various malformed data strings/typos that keep cropping up, including the new typo in the most recent case batch.  Added new test file for new typo.

Fixing ri scrapers

---

juriscraper/__init__.py
juriscraper/opinions/united_states/state/md.py

Adding contact information to md

---

juriscraper/opinions/united_states/state/fladistctapp_1_per_curiam.py

The scraper is failing now, but it's not a problem.  Early in the month, or during months in which no opinions are published, the scraper will fail due to the current month not being available in the portal's 'Release Month' drop down.

Adding helpful exception to fladistctapp_1_per_curiam

---

juriscraper/opinions/united_states/state/idahoctapp_u.py
tests/examples/opinions/united_states/idahoctapp_u_example_2.html

Simplifying and patching to handle date formats in a more standardized way.  Added new example file to cover new format use case.

Fixing idahoctapp_u

---

juriscraper/__init__.py
juriscraper/opinions/united_states/state/fladistctapp_2.py
tests/examples/opinions/united_states/fladistctapp_2_example_5.html

This scraper is probably due for a rewriting, but I'm not committed enough to do it right now.  Patched it to work for a new use case and included new test file for use case coverage.  Also bumping version number.

Fixing fladistctapp_2

---

juriscraper/AbstractSite.py
juriscraper/opinions/united_states/federal_special/armfor.py
juriscraper/opinions/united_states/state/fladistctapp_1_per_curiam.py
juriscraper/opinions/united_states/state/idahoctapp_u.py
juriscraper/opinions/united_states/state/nyappdiv_4th.py
juriscraper/opinions/united_states/state/ohio.py
juriscraper/opinions/united_states/state/sd.py
juriscraper/opinions/united_states_backscrapers/state/idahoctapp_civil.py
tests/examples/opinions/united_states/nyappdiv_4th_example.html

Hey @mlissner, wanted you to review this to make sure it looks good.  mostly want to make sure you think my addition to AbstractSite is okay.  As I mentioned in the slack channel, there is some code in the new method that duplicates what's going on in _download(), though it's not many lines.  I think the real solution would be to extract the get/post handling logic into their own method on AbstractSite (similar to the one I created), then _download() could call those, and they would also be available to all child scrapers to use.  Right now, there are a lot of scrapers that duplicate (more or less) the logic in my new method, most of which could probably be replaced with calls to this new method (or whatever new methods for post/get tat we come up with for AbstractSite).  Let me know what …

Nyappdiv 4th and more

---

juriscraper/sample_caller.py

I think this is the last change needed related to #175 if I'm correct.

fixing sample_caller.py (#175) by making it py3 ready.

---

juriscraper/pacer/notes.md

Explain `number` parameter to `possible_case_numbers.pl` per unminified js comments.

notes.md: explain possible_case_numbers?number=

---

juriscraper/pacer/appellate_docket.py
juriscraper/pacer/docket_report.py

Cleanup not to be squashed

---

juriscraper/pacer/attachment_page.py

attachment_page.py: Add `__main__` debugging driver
Please don't squash style commits with additions.

attachment_page.py: Add __main__ debugging driver

---

juriscraper/pacer/free_documents.py

These were intended to support changes that will probably not land, because they turn out not to be necessary. Although maybe there is a bit of a tail coming to add a `_main` command-line driver and remove some bogon tests.

free_documents.py: Style cleanup

---

juriscraper/pacer/__init__.py
juriscraper/pacer/case_query.py
juriscraper/pacer/docket_report.py

This might be premature, but I'm not sure what more to do with it, so I offer it here, mostly for code review purposes.

Parser for iQuery.pl pages

---

juriscraper/AbstractSite.py

I don't use warnings enough to notice that "raising" a warning promotes it to an exception.  This is to fix a bug in the former PR.

don't elevate warning to exception

---

juriscraper/lib/test_utils.py

Please don't blindly accept this request.  The readme should probably updated.  I am also interested in diminishing the errors into warnings, where y'all can promote the warnings to errors when calling python.

check environment to skip slowness errors

---

juriscraper/lib/utils.py
juriscraper/opinions/united_states/state/alaskactapp.py
juriscraper/opinions/united_states/state/fladistctapp_1_written.py
juriscraper/opinions/united_states/state/fladistctapp_2_per_curiam.py
juriscraper/opinions/united_states/state/fladistctapp_2_written.py
juriscraper/opinions/united_states/state/iowactapp.py
juriscraper/opinions/united_states/state/vtsuperct_civil.py
juriscraper/opinions/united_states/state/vtsuperct_criminal.py
juriscraper/opinions/united_states/state/vtsuperct_environmental.py
juriscraper/opinions/united_states/state/vtsuperct_family.py
juriscraper/opinions/united_states/state/vtsuperct_probate.py
juriscraper/pacer/appellate_docket.py
juriscraper/pacer/attachment_page.py
juriscraper/pacer/case_query.py
juriscraper/pacer/docket_report.py
juriscraper/pacer/hidden_api.py
juriscraper/pacer/internet_archive.py
juriscraper/pacer/reports.py
tests/test_pacer.py

This helps a bit more with preparing for py3.  The "test_everything" fails in py3 and nothing is tested.  There are also json differences when testing in py3 in "test_pacer".  However, everything should be just fine for py2.

Futureproofing

---

juriscraper/opinions/united_states/state/miss.py
juriscraper/opinions/united_states/state/missctapp.py

This just updates the back_scrape_iterable's on the miss and missctapp modules.

Update miss backscrapers

---

juriscraper/opinions/united_states/state/__init__.py
juriscraper/opinions/united_states/state/scctapp.py
tests/examples/opinions/united_states/scctapp_example.compare.json
tests/examples/opinions/united_states/scctapp_example.html

Very similar to S. Carolina Supreme Court; only the URL was changed.

Add Scraper for S. Carolina Ct. of Appeals

---

juriscraper/OpinionSite.py
juriscraper/opinions/united_states/federal_special/tax.py
tests/examples/opinions/united_states/tax_example.compare.json
tests/local/test_text_parsing.py

Add text parsing NOOP to OpinionSite and enable Tax Court specific extraction of citations

283 text parsing

---

juriscraper/sample_caller.py

Create byte string out of download_urls before quoting them

---

juriscraper/pacer/__init__.py
juriscraper/pacer/http.py
juriscraper/pacer/mobile_query.py
tests/examples/pacer/mobile_queries/dcd.html
tests/examples/pacer/mobile_queries/dcd.json
tests/local/test_PacerParseMobileQueryTest.py
tests/network/test_PacerMobileQueryTest.py

Closes https://github.com/freelawproject/juriscraper/issues/315.
Note this just returns the text around cost instead of parsing it. But if this is free, there's no text there, and all you really need to know is if you were charged or not, so this works fine for that.

feat(mobile) Added mobile scraper

---

README.rst
requirements.txt
setup.py

Peg feedparser req, update version and README

---

README.rst
juriscraper/lib/log_tools.py
setup.py

Resolves #347 
Small update that allows consume to control log file location.

updated readme and log tools

---

.gitignore
README.rst
juriscraper/AbstractSite.py
juriscraper/OpinionSiteLinearWebDriven.py
juriscraper/OpinionSiteWebDriven.py
juriscraper/WebDriven.py
juriscraper/opinions/united_states/federal_special/tax.py
juriscraper/opinions/united_states/state/kan_p.py
juriscraper/opinions/united_states/state/mdag.py
juriscraper/opinions/united_states/state/ohio.py
juriscraper/opinions/united_states/state/sd.py
juriscraper/opinions/united_states/state/tex.py
juriscraper/opinions/united_states_backscrapers/federal_appellate/ca5.py
requirements.txt
tests/examples/opinions/united_states/mdag_example_2.compare.json
tests/examples/opinions/united_states/mdag_example_2.html

* update selenium to 4.0.0-alpha-6 to match CourtListener and resolve noisy SSL errors
* replace PhantomJS webdriver with FireFox webdriver
* adjusted WebDriven scrapers that experienced issues
@mlissner, I think/hope the adjustments to the web driven scrapers will work in your remote Chrome webdriver the same way they do in local FireFox, but I don't have an environment to test.  For what it's worth, the PhantomJS and FireFox webdrivers did behave differently in a few cases, but perhaps the behavior change was due to selenium updates rather than the webdrivers (I can't test that theory because this new version of selenium doesn't support PhantomJS).  
I agree with you that it probably best to use the same environment both locally and in your docker remote, otherwise we could run into …

Warning Supression & PhantomJS Replacement 

---

juriscraper/opinions/united_states/federal_appellate/scotus_slip.py

PR Adds Amy Coney Barrett to SCOTUS Slip opinions

feat(scotus_slip): Add Amy Coney Barrett to slip opinions

---

README.rst

Fix broken link in readme

---

juriscraper/lib/html_utils.py
juriscraper/pacer/docket_report.py
juriscraper/pacer/reports.py
setup.py
tests/local/test_DocketParseTest.py

This adds code to anonymize district dockets. Should be pretty simple and clean.

Add anonymizer

---

juriscraper/pacer/reports.py

* Optional parameter with default.
* If provided, also gets added to the POST request.

Added magic_num for first look downloads.

---

juriscraper/pacer/http.py
tests/network/test_PacerAuthTest.py

Changes to local library to create conections to PACER with their new API for authentification.
PACER sent an email requesting to update all authentication requests to their API by **11/21/2021**, when their new authetification system is expected to be released.
Closes: #414

Update PACER authentication to new API

---

juriscraper/opinions/united_states/federal_appellate/__init__.py
juriscraper/opinions/united_states/federal_appellate/cadc_pi.py
tests/examples/opinions/united_states/cadc_pi_example.compare.json
tests/examples/opinions/united_states/cadc_pi_example.html

Adds support for public opinions as suggested in
Issue Fixes #321

feat(cadc_pi): New Scraper for CADC Public Interest

---

juriscraper/lib/importer.py
juriscraper/opinions/united_states_backscrapers/administrative_agency/olc.py

Reset site for each back scrape iterable.
Revert changes to OLC back scraper.

Update site yielder

---

juriscraper/opinions/united_states/state/nm.py
juriscraper/opinions/united_states/state/nmctapp.py
juriscraper/pacer/http.py
tests/examples/opinions/united_states/nm_example.compare.json
tests/examples/opinions/united_states/nmctapp_example.compare.json
tests/local/test_ScraperExtractFromTextTest.py

Upgrade New Mexico and Ct App
Limit to ten opinions to stay under artificial threshold.
Update to pre-commit whitspace

New Mexico

---

juriscraper/opinions/united_states/state/ark.py
juriscraper/opinions/united_states/state/arkctapp.py
tests/examples/opinions/united_states/ark_example.compare.json
tests/examples/opinions/united_states/ark_example.html
tests/examples/opinions/united_states/arkctapp_example.compare.json
tests/examples/opinions/united_states/arkctapp_example.html
tests/local/test_ScraperExtractFromTextTest.py

Updates Arkansas to only scrape 10 opinions at a time for both 
Arkansas and Arkansas Ct of App to deal with 
repeatedly being blocked by Lexum.  The website admin.
Update to opinionsitelinear.

feat(ark): Update Arkansas

---

juriscraper/oral_args/united_states/federal_appellate/cafc.py
tests/examples/oral_args/united_states/cafc_example.compare.json
tests/examples/oral_args/united_states/cafc_example.html

Fixes #514 
Refactor OA CAFC scraper 
Switch to Oral Argument Site Linear
Use JSON response to generate data
Add month back scraper back to start of failing scraper.

fix(cafc): Update cafc oa scraper

---

juriscraper/opinions/united_states/state/masslandct.py
tests/examples/opinions/united_states/masslandct_example.compare.json

Land court was failing URLs and Docket numbers

fix(masslandct): Fix land court

---

juriscraper/oral_args/united_states/state/ill.py
juriscraper/oral_args/united_states/state/illappct_1st_dist.py
juriscraper/oral_args/united_states/state/illappct_2nd_dist.py
juriscraper/oral_args/united_states/state/illappct_3rd_dist.py
juriscraper/oral_args/united_states/state/illappct_4th_dist.py
juriscraper/oral_args/united_states/state/illappct_5th_dist.py
juriscraper/oral_args/united_states/state/illappct_workers_comp.py
tests/examples/oral_args/united_states/ill_example.compare.json
tests/examples/oral_args/united_states/ill_example.html
tests/examples/oral_args/united_states/illappct_1st_dist_example.compare.json
tests/examples/oral_args/united_states/illappct_1st_dist_example.html
tests/examples/oral_args/united_states/illappct_2nd_dist_example.compare.json
tests/examples/oral_args/united_states/illappct_2nd_dist_example.html
tests/examples/oral_args/united_states/illappct_3rd_dist_example.compare.json
tests/examples/oral_args/united_states/illappct_3rd_dist_example.html
tests/examples/oral_args/united_states/illappct_4th_dist_example.compare.json
tests/examples/oral_args/united_states/illappct_4th_dist_example.html
tests/examples/oral_args/united_states/illappct_5th_dist_example.compare.json
tests/examples/oral_args/united_states/illappct_5th_dist_example.html
tests/examples/oral_args/united_states/illappct_workers_comp_example.compare.json
tests/examples/oral_args/united_states/illappct_workers_comp_example.html

Fixes #517
A new website and some changes had broekn all the ill OA scrapers.
Updated tests but did not update backscraper.  Just wanted to get rid of this 
in sentry.  It is our most common error occurring roughly every 14 minutes.

fix(ill-OA): Fix all failing Illinois Oral Argument Scrapers

---

README.rst
juriscraper/pacerdocket.py
sample_caller.py

550 errors readme

---

CHANGES.md
requirements.txt
setup.py

Selenium was updated to the last version 4.4.3 in order to solve CL dependencies issues.

Update selenium version and version bump

---

CHANGES.md
juriscraper/pacer/reports.py

fix(pacer): Fix content vs. text error

---

CHANGES.md
setup.py

version bump v2.5.22

---

juriscraper/opinions/united_states/state/__init__.py

Comment out maine to disable scraping it

feat(state): Remove Maine

---

juriscraper/opinions/united_states/federal_appellate/ca9_p.py
tests/examples/opinions/united_states/ca9_p_example.compare.json
tests/examples/opinions/united_states/ca9_u_example.compare.json

Add case name cleanup to ninth circuit cases

feat(ca9): Add title cleanup for ca9

---

juriscraper/opinions/united_states/federal_special/tax.py

Fix Blue Green Deploy issue with tax court

fix(tax): Fix tax blue/green

---

juriscraper/oral_args/united_states/federal_appellate/cafc.py

Fixes issue #611 
Simply needed to set a variable that was hard coded.

fix(oa-cafc): Fix cafc

---

tests/examples/pacer/dockets/district/cand_7.html
tests/examples/pacer/dockets/district/cand_7.json

Adding this first so that we can see the diff when applying #718.

Add cand docket with attachments

---

CHANGES.md
setup.py

Update to version 2.5.53

---

juriscraper/opinions/united_states/state/mass.py

Update Massachusetts Scraper to handle other PDFs

feat(mass): Fix Mass Scraper

---

juriscraper/pacer/appellate_docket.py
juriscraper/pacer/docket_history_report.py
juriscraper/pacer/docket_report.py
juriscraper/pacer/internet_archive.py

pacer/*: Abstract out date regexs into DATE_REGEX. Document.

2023.10.12.date regex

---

juriscraper/opinions/united_states/state/__init__.py
juriscraper/opinions/united_states/state/or.py
juriscraper/opinions/united_states/state/orctapp.py
tests/examples/opinions/united_states/orctapp_example.compare.json
tests/examples/opinions/united_states/orctapp_example.html

Fixes #707 
Fixes Oregon Supreme Court
Adds Oregon Court of Appeals

fix(Oregon): Fixed Oregon

---

juriscraper/opinions/united_states/state/nh.py

fix(nh): Update URL for API response in NH

---

juriscraper/opinions/united_states/state/ala.py

Alabama no longer needs selenium but
I accidently left it as webdriven
remove it.

fix(ala): Fix alabama

---

juriscraper/opinions/united_states/state/okla.py
juriscraper/opinions/united_states/state/oklaag.py

Fix:
Oklahoma Sup
Oklahoma Civ
Oklahoma Crim
Oklahoma AG
Simply need to encode the HTML response for CL to handle it

fix(okla): Fix Oklahoma

---

juriscraper/opinions/united_states/state/oklaag.py

Fix #765 
Oklahoma is probably fixed and OklaAG just needed a slightly different cleanup method

fix(oklaag): Fix cleanup method for OklaAG

---

juriscraper/opinions/united_states/state/va.py

Virginia Tests 
PR Fixes failing VA tests

fix(va): Fix VA tests

---

juriscraper/opinions/united_states/state/__init__.py
juriscraper/opinions/united_states/state/coloctapp.py
juriscraper/opinions/united_states/state/nev.py
juriscraper/opinions/united_states/state/nevapp.py
tests/examples/opinions/united_states/nev_example.compare.json
tests/examples/opinions/united_states/nevapp_example.compare.json
tests/examples/opinions/united_states/nevapp_example.html

Minor fix for Juriscraper with one enhancement.
Implements #60 
Add Nev Appellate Court
Fix Nevada scraper 
Fix Colorado Appellate Scraper

Minor Fixes and changes

---

juriscraper/AbstractSite.py
juriscraper/opinions/united_states/state/colo.py

Needed to set the date to test
with after initializing
Also - tweak abstractsite to
correctly match backscrapeiterable
design

fix(colo): Update testing

---

juriscraper/opinions/united_states/state/nyclaimsct.py
juriscraper/opinions/united_states/state/nytrial.py
tests/examples/opinions/united_states/nyclaimsct_example.compare.json
tests/local/test_ScraperExtractFromTextTest.py

Also, make nyclaimsct return no child court, since it has no children

fix(nytrial): Citation type in extract_from_text

---

juriscraper/opinions/united_states/state/colo.py
tests/local/test_ScraperExtractFromTextTest.py

"type" field is expected by courtlistener Citation model

fix(colo): add Citation type

---

juriscraper/opinions/united_states/state/lactapp_1.py

Update and use custom SSL Adapter to connect to LA CT APP server

fix(lactapp_1): Fix lactapp_1

---

juriscraper/opinions/united_states/territories/visuper_p.py

fix(visuper_p): refined xpath for valid rows

---

juriscraper/opinions/united_states/state/nev.py
juriscraper/opinions/united_states/state/nevapp.py
tests/examples/opinions/united_states/nev_example.compare.json
tests/examples/opinions/united_states/nevapp_example.compare.json

Nevada Changes 
Add deferring list

fix(nev): Update Nevada for API changes

---

juriscraper/opinions/united_states/state/nev.py
juriscraper/opinions/united_states/state/nevapp.py
tests/examples/opinions/united_states/nev_example.compare.json
tests/examples/opinions/united_states/nevapp_example.compare.json

Update Nevada Opinions Scraper

893 update Nevada

---

juriscraper/opinions/united_states/state/md.py

Quick fix for Maryland courts
Disable verify

feat(md): Disable verify for MD courts

---

juriscraper/opinions/united_states/state/pa.py

Which may not always have an author

feat(pasuperct): Fix pa super ct

---

juriscraper/opinions/united_states/state/fladistctapp.py

Solves #870
Pagination test was true when no pagination menu was available, leading to paginating to inexistent pages

fix(fladistctapp): correct wrong pagination xpath

---

juriscraper/opinions/united_states/federal_special/armfor.py
tests/examples/opinions/united_states/armfor_example.compare.json
tests/examples/opinions/united_states/armfor_example.html

fix arm forces scraper for 2024

fix(armedforces): Fix armed forces scraper

---

juriscraper/opinions/united_states/state/coloctapp.py

The date \<p> no longer has an \<a> tag inside, which was causing the IndexError
Solves #890
Fixes COURTLISTENER-6F4

fix(coloctapp): correct date xpath

---

juriscraper/opinions/united_states/state/tex.py

- Solves #918
- Also, refactor some fstrings and write some comments

fix(tex): modify xpath to skip empty row

---

juriscraper/opinions/united_states/state/nev.py

Small tweak to handle Nevada Court website changes

fix(nev): Fix nev/nevapp

---

juriscraper/opinions/united_states/state/fladistctapp.py

Fix Fla Dist Ct App 5

---

juriscraper/opinions/united_states/state/minnag.py

feat(minnag): Add https to minnag

---

juriscraper/opinions/united_states/state/alaska.py
tests/examples/opinions/united_states/alaska_example.compare.json
tests/examples/opinions/united_states/alaskactapp_example.compare.json

Solves #933.
XPath was picking 2nd cell, which was the numeration of opinions, not the citation string. Also corrected test cases output JSON

fix(alaska): correct citation xpath

---

juriscraper/opinions/united_states/federal_special/__init__.py
juriscraper/opinions/united_states/federal_special/fisc.py
juriscraper/opinions/united_states/federal_special/fiscr.py
tests/examples/opinions/united_states/fisc_example.compare.json
tests/examples/opinions/united_states/fisc_example.html
tests/examples/opinions/united_states/fiscr_example.compare.json
tests/examples/opinions/united_states/fiscr_example.html

feat(fisc): Add scraper for FISA Court and Court of Review

---

juriscraper/lib/html_utils.py
juriscraper/pacer/docket_report.py
requirements.txt

Fixes #980 
Remove deprecated function cleaner
Fix docket report breakage
Update requirements txt file

fix(lxml): Remove deprecated code

---

juriscraper/opinions/united_states/federal_special/afcca.py

feat(afcca): dynamic backscraper

---

juriscraper/opinions/united_states/federal_bankruptcy/bap10.py

feat(bap10): dynamic backscraper

---

juriscraper/opinions/united_states/administrative_agency/olc.py

feat(olc): dynamic backscraper

---

juriscraper/opinions/united_states/state/fla.py

Needed to fill `fla` gap #960
Also, update fla scraper to OpinionSiteLinear

feat(fla): support dynamic backscraper

---

juriscraper/opinions/united_states/state/ill.py
juriscraper/opinions/united_states/state/illappct.py

feat(ill): support dynamic backscraper

---

juriscraper/pacer/email.py
tests/examples/pacer/nef/s3/njb_3.json
tests/examples/pacer/nef/s3/njb_3.txt
tests/examples/pacer/nef/s3/njb_4.json
tests/examples/pacer/nef/s3/njb_4.txt

fix(pacer.email): support multi docket nef for njb

---

juriscraper/pacer/docket_report.py
tests/examples/pacer/dockets/district/txsd_1.html
tests/examples/pacer/dockets/district/txsd_1.json

escape error string punct fixes #1033

---

juriscraper/opinions/united_states/state/nm.py
juriscraper/opinions/united_states/state/nmctapp.py
tests/examples/opinions/united_states/nm_example.compare.json
tests/examples/opinions/united_states/nm_example.html
tests/examples/opinions/united_states/nmctapp_example.compare.json
tests/examples/opinions/united_states/nmctapp_example.html

feat(nm): dynamic backscraper

---

juriscraper/pacer/http.py

This commit refactors the logic responsible for sending login requests used to establish PACER sessions. This improves code maintainability and lays the groundwork for future enhancements.

feat(pacer): Refactor login logic for PACER sessions

---

juriscraper/opinions/united_states/state/wyo.py

Helps solve #997
Also, refactor to OpinionSiteLinear

feat(wyo): dynamic backscraper

---

juriscraper/opinions/united_states/federal_special/nmcca.py

feat(nmcca): dynamic backscraper

---

juriscraper/opinions/united_states/state/tex.py

Assumes backscrape keyword arguments from the dynamic backscraping PR
Solves #944

feat(tex): support dynamic backscraping in tex

---

juriscraper/opinions/united_states/state/alaska.py
juriscraper/opinions/united_states/state/alaskactapp.py

Will help solve Alaska gap issue #937

feat(alaska): add dynamic backscraping support

---

juriscraper/opinions/united_states/administrative_agency/bia.py
tests/examples/opinions/united_states/bia_example.compare.json
tests/examples/opinions/united_states/bia_example.html

Solves freelawproject#1023
Old scraper was targeting a different HTML layout, which caused it to only pick the first row in each scrape
Also, amended opinions were causing a parsing error

fix(bia): update scraper and example files

---

juriscraper/opinions/united_states/state/calag.py

fix(calag): test for citation existance

---

juriscraper/pacer/email.py
tests/examples/pacer/nef/s3/txnb_1.json
tests/examples/pacer/nef/s3/txnb_1.txt
tests/examples/pacer/nef/s3/txnb_2.json
tests/examples/pacer/nef/s3/txnb_2.txt

fix(pacer.email): parse short description for `txnb`

---

juriscraper/opinions/united_states/state/colo.py

Also affects coloctapp. Related to #1062

fix(colo): set expected content type to text/html

---

juriscraper/oral_args/united_states/federal_appellate/cafc.py

Solves #1052
Error was caused by wdtNonce value not being picked up correctly

fix(oral_args.cafc): updated xpath selector

---

juriscraper/opinions/united_states/state/massappct_u.py

fix(massappct_u): add headers attribute required by Courtlistener

---

.github/workflows/tests.yml
requirements-dev.txt
setup.cfg
setup.py

This PR updates the setup.py configuration to address deprecated setuptools options and improves test management using pytest.

Fix deprecated test options and update pytest configuration

---

juriscraper/opinions/united_states/state/minn.py
juriscraper/opinions/united_states/state/minnctapp_p.py
juriscraper/opinions/united_states/state/minnctapp_u.py
tests/examples/opinions/united_states/minn_example.compare.json
tests/examples/opinions/united_states/minnctapp_p_example.compare.json
tests/examples/opinions/united_states/minnctapp_u_example.compare.json

Fixes #1064
- Update scrapers and example files for minn, minnctapp_p, minnctapp_u
- Now returning disposition
- Implement backscraper

fix(minn, minnctapp): Fix SSL error and implement backscraper

---

juriscraper/pacer/email.py
tests/examples/pacer/nef/s3/okeb_1.json
tests/examples/pacer/nef/s3/okeb_1.txt
tests/examples/pacer/nef/s3/okeb_2.json
tests/examples/pacer/nef/s3/okeb_2.txt

Related to #912
- handle `okeb` short description parsing
- add 2 test cases for okeb

fix(recap.email): handle `okeb` short_description parsing

---

juriscraper/opinions/united_states/state/cal.py

Solves #1118
Scrapers were failing with SSLError

fix(cal, calctapp): request[verify]=False and change URL to https

---

tests/examples/pacer/dockets/district/njd_509180.html
tests/examples/pacer/dockets/district/njd_509180.json

https://github.com/freelawproject/juriscraper/pull/1121#issuecomment-2289564443
Added new tests after this comment.

Added njd_509180.html/json files for regression tests

---

.github/workflows/tests.yml
juriscraper/lib/html_utils.py
juriscraper/pacer/docket_report.py
setup.py
tests/examples/pacer/dockets/bankruptcy/kywb_238163.json
tests/examples/pacer/dockets/bankruptcy/nvb_368678.json
tests/examples/pacer/dockets/bankruptcy/vawb_270571.html
tests/examples/pacer/dockets/bankruptcy/vawb_270571.json
tests/examples/pacer/dockets/bankruptcy/waeb_157024.html
tests/examples/pacer/dockets/bankruptcy/waeb_157024.json
tests/examples/pacer/dockets/district/alnb_1.json

Should better handle some newer bankruptcy docket formats.

Various improvements to bankruptcy docket parsing

---

juriscraper/opinions/united_states/federal_appellate/scotus_slip.py

feat(scotus_slip): implement backscraper

---

juriscraper/pacer/docket_history_report.py
tests/examples/pacer/docket_history_reports/casb_463475.html
tests/examples/pacer/docket_history_reports/casb_463475.json

Should handle some newer history report formats better.

Make docket history report parser more robust

---

juriscraper/pacer/attachment_page.py
tests/examples/pacer/attachment_pages/deb_04218015230.json
tests/examples/pacer/attachment_pages/mab_094126221797.json
tests/examples/pacer/attachment_pages/nysb_12604013833_new.html
tests/examples/pacer/attachment_pages/nysb_12604013833_new.json

Seems there was some sort of update which changed the attachment page format for bankruptcy cases.

Handle new bankruptcy attachment page format

---

juriscraper/pacer/internet_archive.py
tests/examples/pacer/dockets_internet_archive/almd_49523.json
tests/examples/pacer/dockets_internet_archive/azd_1061043.json
tests/examples/pacer/dockets_internet_archive/azd_318008.json
tests/examples/pacer/dockets_internet_archive/cacb_1669936.json
tests/examples/pacer/dockets_internet_archive/cand_194617.json
tests/examples/pacer/dockets_internet_archive/cand_287492.json
tests/examples/pacer/dockets_internet_archive/dcd_119997.json
tests/examples/pacer/dockets_internet_archive/flmd_330522.json
tests/examples/pacer/dockets_internet_archive/nysd_476194.json
tests/examples/pacer/dockets_internet_archive/ohsd_141796.json
tests/examples/pacer/dockets_internet_archive/ohsd_170541.json
tests/examples/pacer/dockets_internet_archive/txnd_202294.json
tests/examples/pacer/dockets_internet_archive/utd_103577.json

Probably needed to make [#4352](https://github.com/freelawproject/courtlistener/pull/4352) work correctly

Use nested attachment format for IA parser

---

juriscraper/opinions/united_states/state/vt.py

Solves #1140
They were blocking the "Juriscraper" user agent

fix(vt): activate needs_special_headers flag

---

juriscraper/opinions/united_states/state/ky.py

fix(ky): skip rows with no documents

---

juriscraper/pacer/email.py
tests/examples/pacer/nef/s3/arwb_1.json
tests/examples/pacer/nef/s3/arwb_1.txt
tests/examples/pacer/nef/s3/arwb_2.json
tests/examples/pacer/nef/s3/arwb_2.txt

fix(pacer.email): parse short description for `arwb`

---

juriscraper/opinions/united_states/state/coloctapp.py

Helps solve:
- https://github.com/freelawproject/courtlistener/issues/4443
- #1094
Implement cleanup_content, only for coloctapp:
-  to remove tags with tokens that changed every scrape, altering the hash and causing duplicates
- to remove classes that conflicted with CL classes and messed up the diplay

feat(coloctapp): implement cleanup_content

---

juriscraper/opinions/united_states/federal_appellate/cadc_u.py

Solves #1181
XML title tag had changed, updated the getter so scraper keeps working

fix(cadc_u): change docket number getter

---

juriscraper/oral_args/united_states/federal_appellate/ca11.py

fix(oral_args.ca11): update to OralArgumentSiteLinear

---

juriscraper/OralArgumentSite.py
juriscraper/OralArgumentSiteLinear.py
juriscraper/oral_args/united_states/federal_appellate/cadc.py
tests/examples/oral_args/united_states/cadc_example.compare.json
tests/examples/oral_args/united_states/cadc_example.html

Add quick fix for CADC 
Add back scraper for missing months

Update oa cadc

---

juriscraper/opinions/united_states/state/neb.py

fix(neb): handle row with no link

---

juriscraper/opinions/united_states/state/kan_p.py
juriscraper/opinions/united_states/state/kan_u.py
juriscraper/opinions/united_states/state/kanctapp_p.py
juriscraper/opinions/united_states/state/kanctapp_u.py
tests/examples/opinions/united_states/kanctapp_p_example.html
tests/examples/opinions/united_states/kanctapp_u_example.html

Solves #1222
- scraper was not applying filters; wrong data must be cleaned on the DB level

fix(kan, kanctapp): scraper now applies filters

---

juriscraper/opinions/united_states/state/ohio.py
tests/examples/opinions/united_states/ohioctcl_beginningofyear_example.compare.json
tests/examples/opinions/united_states/ohioctcl_beginningofyear_example.html
tests/examples/opinions/united_states/ohioctcl_example.compare.json
tests/examples/opinions/united_states/ohioctcl_example.html

Fix Ohio Ct Apps and associated tests

Fix ohio ct apps

---

juriscraper/opinions/united_states/state/colo.py
juriscraper/opinions/united_states/state/coloctapp.py
tests/examples/opinions/united_states/colo_example.compare.json
tests/examples/opinions/united_states/coloctapp_example.compare.json

Scrape the PDFs from ct app
Fix status and refactor a little

feat(colo): Update colorado

---

juriscraper/opinions/united_states/state/okla.py

fix(okla): skip row with no docket number

---

juriscraper/opinions/united_states/federal_appellate/cafc.py

fix(cafc): add request[verify]=False to bypass SSL errors

---

juriscraper/AbstractSite.py
juriscraper/lib/importer.py
juriscraper/lib/utils.py
juriscraper/opinions/united_states/state/lactapp_1.py
juriscraper/opinions/united_states/state/nd.py
juriscraper/opinions/united_states/state/ohio.py

Solves #1294
- implement ohio backscraper
- refactors utils.backscrape_over_paginated_results so it's usable with POST request scrapers
- refactros nd and lactapp_1 that used the function so they still work
- AbstractSite.make_backscrape_iterable now returns dates; before it was mixing date and datetime

feat(ohio): implement backscraper

---

CHANGES.md
juriscraper/opinions/united_states/state/mont.py

fix(mont): add conditional to cleanup_content

---

CHANGES.md
juriscraper/opinions/united_states/state/colo.py

Solves #1340; site was blocking "Juriscraper" user agent

fix(colo, coloctapp): change default user agent

---

CHANGES.md
juriscraper/opinions/united_states/federal_appellate/ca7.py
juriscraper/oral_args/united_states/federal_appellate/ca7.py

fix(ca7): url from http to https

---

CHANGES.md
juriscraper/opinions/united_states/federal_appellate/ca8.py

fix(ca8): fix SSLError by setting request[verify] to False

---

CHANGES.md
juriscraper/opinions/united_states/federal_special/uscgcoca.py

fix(uscgcoca): fix citation regex

---

CHANGES.md
juriscraper/oral_args/united_states/state/ill.py

fix(oral_args.ill): check if audio file link exists

---

CHANGES.md
juriscraper/opinions/united_states/state/__init__.py
juriscraper/opinions/united_states/state/me.py
tests/examples/opinions/united_states/me_example.compare.json
tests/examples/opinions/united_states/me_example_2.compare.json
tests/examples/opinions/united_states/me_example_3.compare.json
tests/local/test_ScraperExtractFromTextTest.py

Add backscraper
Add opinionsite linear
Update tests
Add extract from text for more information

fix(maine): Update maine

---

CHANGES.md
juriscraper/opinions/united_states/state/nh_p.py

fix(nh): update user agent string

---

CHANGES.md
juriscraper/opinions/united_states/administrative_agency/bia.py

fix(bia): update date_filed extraction

---

CHANGES.md
juriscraper/opinions/united_states/state/or.py
juriscraper/opinions/united_states/state/ortc.py
tests/local/test_ScraperExtractFromTextTest.py

Solves #1226
Allows to collect regional P3d citations for `or` and `orctapp`

feat(or): implement extract from text

---

CHANGES.md
juriscraper/opinions/united_states/administrative_agency/bia.py
tests/local/test_ScraperExtractFromTextTest.py

- Fix `bia` extract_from_text method
- Add test cases

fix(bia): Update bia scraper with tests

---

CHANGES.md
setup.py

version bump v2.6.68

---

CHANGES.md
juriscraper/opinions/united_states/state/__init__.py
juriscraper/opinions/united_states/state/ncbizct.py
tests/examples/opinions/united_states/ncbizct_example.compare.json
tests/examples/opinions/united_states/ncbizct_example.html

feat(ncbizct): new scraper for North Carolina Business Court

---

CHANGES.md
juriscraper/opinions/united_states/territories/prapp.py

Address #1403 
Fixes `prapp` and adds backscraper

Fix `prapp` with backscraper

---

CHANGES.md
juriscraper/opinions/united_states/state/sd.py
tests/examples/opinions/united_states/sd_example.compare.json
tests/examples/opinions/united_states/sd_example.html

fix(sd): Tweak row xpath and url xpath

---

CHANGES.md
pyproject.toml
uv.lock

This PR updates the project version and tweaks the `CHANGES.md` file to include a new release, reorganize sections, and document changes.

chore: version bump v2.6.79

---

CHANGES.md
juriscraper/opinions/united_states/state/neb.py
tests/local/test_ScraperExtractFromTextTest.py

Fixes #1549
Will help collect state citations for older opinions that did not get their citations assigned

feat(neb, nebctapp): implement extract_from_text

---

CHANGES.md
juriscraper/opinions/united_states/administrative_agency/bia.py
tests/examples/opinions/united_states/bia_example.compare.json

Solves #1574
Page had changed, parsers needed to be updated

fix(bia): update xpath parsers

---

CHANGES.md
juriscraper/opinions/united_states/state/conn.py

fix(conn): update parser to handle bad source HTML

---

CHANGES.md
juriscraper/opinions/united_states/state/ariz.py
juriscraper/opinions/united_states/state/arizctapp_div_2.py
tests/local/test_ScraperExtractFromTextTest.py

This pull request enhances the extraction of lower court information for Arizona state court opinions.
this PR addresses in part --#1569

feat(ariz): implement lower court and judge extraction from scraped text

---

CHANGES.md
juriscraper/opinions/united_states/state/delaware.py
juriscraper/opinions/united_states/state/delch.py
juriscraper/opinions/united_states/state/delctcompl.py
juriscraper/opinions/united_states/state/delsuperct.py
tests/local/test_ScraperExtractFromTextTest.py

This pull request enhances the Delaware state court scraper by adding support for retrieving lower court information.

feat(del): implement lower court extraction for Delaware scraper
